### ISSUE TITLE
cannot click a radio button

### ISSUE THREAD

**Issue by wyllys66** [Dhruv-Techapps/auto-click-auto-fill#100]
**Describe the bug**
Trying to auto click a radio button, but it never works.  I've double checked the URL and the XPath and they are correct, but whenever I load the page it never selects the item.

For a radio button, is it correct to set the action value to be:  ClickActions::["click"] ?

Using Mac OS/X with Chrome version 79.0.3945.130 (Official Build) (64-bit)

**Comment by Dhruv-Techapps** [comment]
Can you please provide us more details. the page on which you are trying to click and radio button which you trying to select.

If you cant provide information here please share it with us on [email](mailto:dhruv.techapps@gmail.com)
