### ISSUE TITLE
Error when subscribing

### ISSUE THREAD

**Issue by opvpie** [Dhruv-Techapps/auto-click-auto-fill#103]
Hi, I've got two issues (the 2nd I believe is related to the first)

1-Can't upgrade for new functionalities (internal error server) - img attached (error on bottom)

2-I'd like to click on a google ad. The reason I believe it's not working is because the task (action) is being triggered too fast so I need subscription for Init Wait + Xpath + Event trigger. 

![Captura de Tela (91)](https://user-images.githubusercontent.com/63098616/78346649-b23a2580-7575-11ea-8570-301c152d4606.png)

**Comment by Dhruv-Techapps** [comment]
Subscription is provided by Google API and it dont work under VPN. If you have VPN enabled for your browser please disable and retry.

**Comment by Dhruv-Techapps** [comment]
https://getautoclicker.com/docs/subscription
