### ISSUE TITLE
Firefox issue - click different buttons, same site, different pages

### ISSUE THREAD

**Issue by Legalien** [Dhruv-Techapps/auto-click-auto-fill#104]
First of all, I love the extension. I'm using it on Firefox version 55.0.2.

An issue I encountered is as follows.

I installed the extension and made it click the Login button on a website. Whenever that website loads, that button is clicked.

Then I also wanted to add another click, so that something else is clicked after logging in. And it didn't work, until I removed the login click I initially put in.

I tried everything I could, and I could not get the extension to work on both things. It would either click the Login button on the homepage, or the other button after logging in. I could never get it to work on both.

I tried different URL variations, tried adding the commands to the same Configuration instance, tried different configuration instances, and could not get it work. I even googled hoping to find a way to install the same extension twice, so that I could have one extension click the login button, and one click the other button after logging in.

So I don't know, any ideas?

**Comment by hien4990** [comment]
i cannot use it on firefox, get extension time out error, in chrome it work fine, do you know why?

**Comment by dharmesh-hemaram** [comment]
We have stoped firefox support as one of main feature of extension is now not supported by firefox browser
