### ISSUE TITLE
can you add action close tap after click 

### ISSUE THREAD

**Issue by egphp** [Dhruv-Techapps/auto-click-auto-fill#105]
can you add action close tap after click 

that's will help

**Comment by Dhruv-Techapps** [comment]
Hi @egphp ,

Thank you for using our extension. You can add more than once task in queue by clicking + icon. this way you can add more than one task

**Comment by dharmesh-hemaram** [comment]
It is a restriction from a browser. 

`Scripts may close only the windows that were opened by them.`
