### ISSUE TITLE
Delete button and list of tasks

### ISSUE THREAD

**Issue by ivan1d** [Dhruv-Techapps/auto-click-auto-fill#106]
It is very easy to press the massive delete button by mistake and in doing so deleting a task, for double pressing it deleting two tasks in this way.
In addition, the tasks should have a multi lines drop down, so it would be easy to see all tasks created and select accordingly

**Comment by Dhruv-Techapps** [comment]
Hi @ivan1d ,

We would happy bring the new changes suggested by you. But can you provide more details with screen shot.

**Comment by dharmesh-hemaram** [comment]
Refer #118 - this feature is already implemented and available in [Beta version](https://chrome.google.com/webstore/detail/nmcpliniiebkbdehpgicgfcidgkpepep?authuser=0&hl=en)
