### ISSUE TITLE
Add functions to Action: Play sounds and display notifications + open external website + send emails/phone notifications

### ISSUE THREAD

**Issue by ivan1d** [Dhruv-Techapps/auto-click-auto-fill#107]
Recommended additional functionalities for Action:
1. when a specific event occurs the user may need to be informed with the following:
- play sounds
- display a notifications/alert
- send an email
- send a notification to a phone
2. when a specific event occurs it may be needed to open different page or external website (and eventually perform automatic actions actions on that page)

**Comment by tksoh** [comment]
+1

**Comment by dharmesh-hemaram** [comment]
Hi,

[Beta version](https://chrome.google.com/webstore/detail/nmcpliniiebkbdehpgicgfcidgkpepep?authuser=0&hl=en)

we have now added `notification` with `sound` on completion of `action` / `batch` / `configuration` / `onError`

![image](https://user-images.githubusercontent.com/2290202/102056199-02aa9800-3e12-11eb-96eb-45ba506a983b.png)

**Comment by dharmesh-hemaram** [comment]
Soon we will find a way to trigger mail / sms you on completion of the action. We are looking for free SMP server which can send you sms / mail.

**Comment by dharmesh-hemaram** [comment]
Putting on-hold as we need to find a suitable SMTP server to use for this service.

**Comment by PerryFromHolland** [comment]
I'm using the sound feature  all the time now, great!!

**Comment by dharmesh-hemaram** [comment]
Mobile notification is out https://blog.getautoclicker.com/2021/06/auto-clicker-auto-fill-3.2.9/
