### ISSUE TITLE
Multiple button click

### ISSUE THREAD

**Issue by hamza23659** [Dhruv-Techapps/auto-click-auto-fill#108]
first of all i don't really know if its a bug but i am surely looking for help here
so i have to click on a button on website so it takes me to a certain page then redirects me to same page back again
previously your ext has been working fine and i appreciate your work <3
now the site has taken down action against autos maybe idk but the button i had to click now changes its position everytime page refreshes.
there are like 8 block space on where it would appear next but i'm not certain where because its random
now the problem i'm having with extension is that i can make all 8 blocks xpath to it but it doesn't work it only auto clicks on one block
like if i had put block #1 on extension first and other 7 blocks after it no matter which block the button may appear the extension will only recognize block#1 and only work with it
kindly reply please

**Comment by Dhruv-Techapps** [comment]
You can try with absolute [xpath ](https://getautoclicker.com/docs/xpath) instead of relative xpath.

If you find difficulty in generating absolute xpath do drop us [email](mailto:dhruv.techapps@gmail.com) we will help you finding same.
