### ISSUE TITLE
can't enter random values in init wait and repeat interval

### ISSUE THREAD

**Issue by tksoh** [Dhruv-Techapps/auto-click-auto-fill#116]
Hi. 

According to the documentation, we can enter the random number in the form of "1e4 (Random value between 1 to 4)"  in Init Wait and Repeat Interval. However, somehow I can't enter the random values into these fields, as they will only accept numerical values. FYI, I am running Chrome version 84.0.4147.125 on Windows 10 version 2004. Appreciate if anyone can please help clarify.

Thanks.

**Comment by dharmesh-hemaram** [comment]
Hi,

[Beta version](https://chrome.google.com/webstore/detail/nmcpliniiebkbdehpgicgfcidgkpepep?authuser=0&hl=en)

we have fixed this issue in beta version and now you type repeat and repeat interval with random values
