### ISSUE TITLE
can't activate PRO subscription on Microsoft Edge (with Chromium)

### ISSUE THREAD

**Issue by tksoh** [Dhruv-Techapps/auto-click-auto-fill#119]
I am trying to run this extension on Microsoft Edge (don't ask me why ;-), which now come with Chromium support in Version 84.0.522.59. I am able to get the extension installed and running seemingly without issue on the free (non PRO) version. 

However, when I tried to activate the PRO subscription, I am met with some errors when I went into the Get Subscription page. First, when I click on the Check Registration button, a message at the bottom of the page says **"No Registration Found"**, Then, when I click on Subscribe, the message says **"There was an error. Please try again. (Error type: INTERNAL_SERVER_ERROR)"**. When I went into Google Payment Center, it shows that the subscription is ACTIVE. I do not mind paying for another subscription, as long as I can get this working.

FYI, I have disabled PRO subscription and uninstalled the extension from Google Chrome.

Appreciate if anyone can help on this.

**Comment by dharmesh-hemaram** [comment]
We are working on providing global solution

**Comment by dharmesh-hemaram** [comment]
We have removed the subscription part from all our extension versions and now they are totally free.
