### ISSUE TITLE
List of Values To Be Added in Web Form

### ISSUE THREAD

**Issue by chrismccoydotco** [Dhruv-Techapps/auto-click-auto-fill#122]
I have an automation set up for Auto Clicker but now I'm looking to have it run through a list of values to be entered into a field. 

Please see this video: https://www.loom.com/share/134bfc603a664da18294c51c38edc5ae

Is this possible with Auto Clicker? If so, how can I achieve this?

If it is not possible currently, is this a feature that could be added?

**Comment by dharmesh-hemaram** [comment]
Hi @chrismccoydotco ,

We are bringing this feature in next release . where you can upload set of data from csv file and refer them one by one. We will update you once its available for testing

**Comment by chrismccoydotco** [comment]
Ok great, thank you!

**Comment by dharmesh-hemaram** [comment]
We have developed a separate page to fill in data and you can refer those data into the Auto Clicker extension using the Sheet command. It's still under testing phase only.

`Sheet::sheet-name::A1`

Ref: https://getdataentry.com/docs/3.1/getting-started/introduction/
