### ISSUE TITLE
Enhancement Request - xpath not found selection performed at the Action Level

### ISSUE THREAD

**Issue by t0212dah** [Dhruv-Techapps/auto-click-auto-fill#123]
Hello and let me first say thank you for auto-click-auto-fill. I have been using it for a couple of weeks and I love it!  There is one issue I ran into while creating a workflow across several URLs.  In one of the URLs I need to perform a Skip if the xpath is not found however in another URL I need to perform a Retry Refresh.  Because the xpath not found action is in Settings it is a global selection for all URL Actions.  

My request is that the xpath not found selection be made at the Action Level so I can select multiple options throughout my workflow.  Thank you for your consideration.

PS For anyone else who is experiencing this issue, I created a workaround by installing both the Stable and Beta versions. One version is set up for Skip and the other for Retry Refresh.  I split my URLs across the versions based on which setting was needed.  My fear is that once auto-click-auto-fill goes to a single stable version, I'll lose this workaround.

**Comment by dhruv-choudary** [comment]
Hi @t0212dah ,

Action level settings are coming soon. we have developed and its under testing phase and soon will be live

![image](https://user-images.githubusercontent.com/75973635/103147959-62912f00-4780-11eb-9b36-08737b118149.png)

**Comment by dharmesh-hemaram** [comment]
Fixed and available in [v3.1.4](https://chrome.google.com/webstore/detail/cpjikgcdmhfnmaiibplplldlchbjejel?authuser=0&hl=en)
