### ISSUE TITLE
Cannot get it to start/work

### ISSUE THREAD

**Issue by keomo** [Dhruv-Techapps/auto-click-auto-fill#124]
Need Auto click to click a button that says "Next" after a countdown. Right clicked the button and clicked Auto Clicker. What are my next steps to get it to start?

**Comment by dharmesh-hemaram** [comment]
For a quick start refer below

Video: https://www.youtube.com/watch?v=M3yNuBkJW3g&t=2s
Wiki: https://getautoclicker.com/docs/getting-started
