### ISSUE TITLE
ExecCommand::paste

### ISSUE THREAD

**Issue by ahmetbaziki** [Dhruv-Techapps/auto-click-auto-fill#126]
All functions work normally but paste command does not work.
I select the object and write "ExecCommand :: paste" in the value part, but it still doesn't work. What can I do?

**Comment by dhruv-choudary** [comment]
ExecCommand are no longer supported by browser and hence our extension as well.

Ref : https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#browser_compatibility
