### ISSUE TITLE
Can not type in -2 for endless repeat

### ISSUE THREAD

**Issue by SamLue** [Dhruv-Techapps/auto-click-auto-fill#127]
It is not possible to type a - for -2
And you show -2 as value for endless repeat in your help.
![repeat](https://user-images.githubusercontent.com/33001794/100475271-fd93dc00-30e2-11eb-9bb4-2b866c323b0b.jpg)

**Comment by dharmesh-hemaram** [comment]
Thank you @SamLue for pointing out we have already fixed this in our upcoming release for quick fix you can type in note pad and copy paste -2
