### ISSUE TITLE
Hover over event is missing

### ISSUE THREAD

**Issue by Hol-o** [Dhruv-Techapps/auto-click-auto-fill#128]
Xpath for button generated with hover doesn't work.
It is possible to generate xpath to specific button but since it's created dynamically it is not working properly.
//*[@id="container"]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/button[1]

**Comment by dharmesh-hemaram** [comment]
We are planning to add five more mouse events `mouseover`, `mouseenter`, `mouseleave`, `mouseout`, 'mousemove`

**Comment by dharmesh-hemaram** [comment]
Fixed and available in [v3.1.4](https://chrome.google.com/webstore/detail/cpjikgcdmhfnmaiibplplldlchbjejel?authuser=0&hl=en)
