### ISSUE TITLE
I need help! Repeated clicks  

### ISSUE THREAD

**Issue by Lundy8899** [Dhruv-Techapps/auto-click-auto-fill#129]
I'm setting automatic click
But there are multiple identical clicks
code:
`<label class="button-text">click</label>  
<label class="button-text">click</label>   
<label class="button-text">click</label>  
<label class="button-text">click</label> 
 <label class="button-text">click</label> `
 I set//label[contains(text(),'click')] 
Then it will click 5 times, and each will click 

How to make it only click once?

**Comment by dharmesh-hemaram** [comment]
You can include parent and use the index to select a particular button 

`//div[@id=parent]/label[1]`
