### ISSUE TITLE
Cannot open Config page

### ISSUE THREAD

**Issue by matos0187** [Dhruv-Techapps/auto-click-auto-fill#130]
Its simples, when i try to click in Autoclick extension trying to reach config page as usual, its sends me to google store. Even when i try to right click, it keeps redirecting me. 

https://stable.getautoclicker.com/ auto refresh to > https://getautoclicker.com/ always. i cant do nothing.

Any clue to solve this? thanks

**Comment by dhruv-choudary** [comment]
Hi @matos0187 ,

We have recently done domain upgrade for configuration page https://stable.getautoclicker.com/ .
- It can be a cache issue please clear your browser cache
- If you have backup of existing configuration remove extension and do fresh installation of same and import back configuration
- Currently our backup page is still up you can visit https://getautoclicker.com/options_page/ page to do your configuration.

We will keep you posted on this issue
