### ISSUE TITLE
Action executed more times than configured

### ISSUE THREAD

**Issue by Hol-o** [Dhruv-Techapps/auto-click-auto-fill#131]
**Describe the bug**
Hi!
With the config made like on screenshot below actions configured should repeat 300 times in total ((2 buttons * 149 repeats) + (2 * 1 initial click)).
Unfortunately it makes over 400 clicks and I'd like to ask you to verify why this is happening.

**To Reproduce**
1. Make the configuration like on screenshot below
2. Run it

**Expected behavior**
Number of repeats is higher than configured.

**Screenshots**
![Screenshot 2020-12-16 at 12 50 29](https://user-images.githubusercontent.com/75253694/102468876-5e636400-4052-11eb-981b-60e4592c390e.png)

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser Chrome
 - Version 87.0.4280.88 64bit

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
I believe this might have something to do with the amount of repeats for buttons.
Due to specifics of the website I'm using it on, sometimes button is clicked in 1 attempt of 3 repeats, sometimes in 2 of 3, and sometimes in 3 of 3.
When button is clicked, it becomes locked and cannot be clicked in this attempt.
What happens with repeats that were not 'used'?

**Comment by dharmesh-hemaram** [comment]
Hi @Hol-o ,

Thank you for using our extension. we have informed the team to look into it.

**Comment by dhruv-choudary** [comment]
Currently interval is not supported with decimal numbers 

this ticket is blocked and will continue once #148 (decimal number in interval) is closed.

**Comment by dharmesh-hemaram** [comment]
Hi @Hol-o ,

We have fixed some of the issues related to init wait with decimal numbers also repeat field doesn't support Random number. So try plain number and not `0e2`

Please retry now and let us know if you still face the issue with an executed count.

> Note: When you set to repeat 5 it will totally run 6 times. 1 time it runs by default and 5 times repeat.
