### ISSUE TITLE
Can't view/edit configuration when disabled

### ISSUE THREAD

**Issue by tksoh** [Dhruv-Techapps/auto-click-auto-fill#133]
When a configuration is disabled, it's detail is completed hidden, so we are unable to tell what the configuration is doing in order to edit, or decide if we are to enable it again.

Please allow the disabled configurations to be viewed and edited.

I am on Windows 10 with google chrome Version 87.0.4280.88 (Official Build) (64-bit).

**Comment by dharmesh-hemaram** [comment]
Hi @tksoh ,

Thank you for using our extension. We understand your issue that once we disable configuration all its fields get hidden. It was done purposely to make user aware that it disables but We will think of an alternate way to highlight and make user aware that it disabled and will not run on the browser.

### Do let us know if you have any suggestions for us on how to show disabled view for usesr.

**Comment by tksoh** [comment]
To me, the blue vs gray color on the 'Enable' check button is already obviously enough.

However, if you are really concerned that it might still not be clear enough, perhaps you can first present the disabled configure the detail hidden, and add a "show configuration" button to let user click on to reveal the detail?

**Comment by dharmesh-hemaram** [comment]
@tksoh , Thank you for your suggestion.

**Comment by dharmesh-hemaram** [comment]
Hi @tksoh ,

we have implemented and made the above feature live with version 3.1.5

[Extension link](https://chrome.google.com/webstore/detail/auto-clicker-autofill-dev/cpjikgcdmhfnmaiibplplldlchbjejel)

New features: 
- https://getautoclicker.com/docs/3.1/extension/icon/
- https://getautoclicker.com/docs/3.1/extension/log/

[Blog](https://blog.getautoclicker.com/) | [Examples](https://examples.getautoclicker.com/) | [Discord](https://discord.gg/hArVQns)
