### ISSUE TITLE
Add counters to the extension

### ISSUE THREAD

**Issue by Hol-o** [Dhruv-Techapps/auto-click-auto-fill#135]
**Is your feature request related to a problem? Please describe.**
I'm missing the option to see counters in different way than current notifications.

**Describe the solution you'd like**
Counters would cover:
- how much actions has been executed
- how much are pending, number of errors
- statistics of last actions (repeat time - useful when you give for example 600e660, was the action completed successfully)
- overall statistics (avg repeat time, success rate)

**Describe alternatives you've considered**
I don't know if extensions allow to add some overlay window on the page but if that would be configurable I believe it would work

**Additional context**
-

**Comment by dharmesh-hemaram** [comment]
### Thank you for your valuable feedback @Hol-o,

We will surely bring the above feature in the upcoming milestone.

**Comment by dharmesh-hemaram** [comment]
Hi @Hol-o ,

we have implemented and made above feature live with version 3.1.5

[Extension link](https://chrome.google.com/webstore/detail/auto-clicker-autofill-dev/cpjikgcdmhfnmaiibplplldlchbjejel)

Docs : 
- https://getautoclicker.com/docs/3.1/extension/icon/
- https://getautoclicker.com/docs/3.1/extension/log/

[Blog](https://blog.getautoclicker.com/) | [Examples](https://examples.getautoclicker.com/) | [Discord](https://discord.gg/hArVQns)
