### ISSUE TITLE
Pls re-implement colour changing Chrome extension icon 

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#136]
In version 3.0.0 the A icon (from AutoClicker) in Chrome extension tray was grey and when doing something went yellow.
Now in version 3.1.4 it stays only yellow. The change of colour was a very nice indicator for me AutoClicker was doing something on the particular webpage.
Now it's always yellow missing that functionality...

If you like the A icon to be yellow all the time, no problem.
Sort of traffic light, yellow means waiting for action.
When its't doing something make it green.

Hope you can re-implement this again!
 Thank you 😃

**Comment by dharmesh-hemaram** [comment]
Thank you for your valuable feedback @PerryFromHolland.

We are working on the above changes.

**Comment by dharmesh-hemaram** [comment]
Hi @PerryFromHolland ,

we have implemented and made above feature live with version 3.1.5

[Extension link](https://chrome.google.com/webstore/detail/auto-clicker-autofill-dev/cpjikgcdmhfnmaiibplplldlchbjejel)

Docs : 
- https://getautoclicker.com/docs/3.1/extension/icon/
- https://getautoclicker.com/docs/3.1/extension/log/

[Blog](https://blog.getautoclicker.com/) | [Examples](https://examples.getautoclicker.com/) | [Discord](https://discord.gg/hArVQns)

**Comment by PerryFromHolland** [comment]
Perfect, thank you so much 👍
