### ISSUE TITLE
Extension load document/window able to set per configuration   

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#137]
Would like to have the possibility to set Extension Load setting Document or Window separately per Configuration.

Some pages won't work with Document setting, so need Window setting.
But for other Document setting works and is much faster, for some even only setting Document works

**Comment by dharmesh-hemaram** [comment]
### Thank you for your valuable feedback @PerryFromHolland.

We will surely bring the above changes in the upcoming milestone.

**Comment by dharmesh-hemaram** [comment]
### Available with v3.1.11 on DEV and BETA
Blog - https://blog.getautoclicker.com/2021/01/auto-clicker-auto-fill-3.1.9/
Doc - https://getautoclicker.com/docs/3.1/configuration-settings/extension-load/

![](https://blog.getautoclicker.com/icons/beta_icon48.png) ![](https://blog.getautoclicker.com/icons/dev_icon48.png)
