### ISSUE TITLE
R-interval and Init-Wait in milliseconds instead of seconds

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#139]
Would like the possibility to set waits and refreshing below 1s or even at 1.5s sometimes, anywhere in AutoClicker
Using **ms** instead of **s** would solve this

**Comment by dharmesh-hemaram** [comment]
Hi @PerryFromHolland,

You can use miliseconds now also refer below docs

https://getautoclicker.com/docs/3.1/configuration/init-wait/

### Examples

- 1
- 1.5
- 0.5
- 2
- 1e4 (Random value between 1 to 4)
- Leave it blank / empty to start right away

**Comment by PerryFromHolland** [comment]
Thanks for your message.

I didn’t know…have to read the docs before asking 😉 Sorry…

Now very happy I can use that!

Cheers,

Perry.

 

Van: Dharmesh <notifications@github.com> 
Verzonden: woensdag 6 januari 2021 17:13
Aan: Dhruv-Techapps/auto-click-auto-fill <auto-click-auto-fill@noreply.github.com>
CC: PerryFromHolland <mailnaarperry@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Dhruv-Techapps/auto-click-auto-fill] R-interval and Init-Wait in milliseconds instead of seconds (#139)

 

Hi @PerryFromHolland <https://github.com/PerryFromHolland> ,

You can use miliseconds now also refer below docs

https://getautoclicker.com/docs/3.1/configuration/init-wait/


Examples


*	1
*	1.5
*	0.5
*	2
*	1e4 (Random value between 1 to 4)
*	Leave it blank / empty to start right away
