### ISSUE TITLE
Enhancing sound/notification possibilties

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#141]
I'm using the sound feature all the time now, great new config option!
Only mssing the possibilty for a sound only on Error or only Action or only whatever other (or combination of events).

1. I suggest ON/OFF setting for sound. And ON/OFF setting for notification. Per Event
2. Possible to set at Event start and Event completion

(3.) If also own custom sounds could be choosen this would be fun, but this is no must.
Else maybe different integrated sounds per event?

Version used 3.1.5 on Chrome (WIN)

**Comment by dharmesh-hemaram** [comment]
Hi @PerryFromHolland ,

For now, we are skipping this ticket and bring a new feature which is pushing notifications on mobile once completed/on Error.

Reason: for every new condition added extension gets slower. Whatever user choice is whether to opt-in/opt-out for notification and sound.

The extension has to do check for that condition and move forward. even if the user opts-out for notification extension must have to do check for user input.

Do let us know if you have any other thoughts.

> Push Notification is limited to on-error/on-config because. They need a server which costs. We initially check for server bandwidth and if very few users make use of it. We will try to add these features for other breakpoints (Action, Batch) completion as well

**Comment by PerryFromHolland** [comment]
Hi, thank you for your message.
Yes the main thing is keeping the extension as fast as possible. So no
problem to put this rfc on hold for now. Maybe later some of my request can
still be implemented without losing speed. For now no hurry, is only a nice
to have.

Setting for each configuration to force Document or Window mode has a much
higher priority for me (issue #137).

Best regards,
Perry


Op vr 29 jan. 2021 13:02 schreef Dharmesh <notifications@github.com>:

**Comment by dharmesh-hemaram** [comment]
Yes we are working on #137 .
