### ISSUE TITLE
Drag and drop Action Steps

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#142]
In version 3.0.0 it was possible to drag and drop Action Steps. Now have to push arrows and sometimes in long batches are getting completely lost what step I'm moving. Please re-implement drag and drop for this

**Comment by PerryFromHolland** [comment]
I could name my Action Steps I realize now. But still drag an drop would be easier ;-)

**Comment by dhruv-choudary** [comment]
Hi @PerryFromHolland ,

Thank you for letting us know that you really like drag and drop feature of action , we will bring back that feature again in our upcoming releases.
