### ISSUE TITLE
Possibilty to sort/re-order Configuration Names

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#143]
First Configuration created stays first in list (at top of the screen)
I would like the possibility to alphabetically order.
Also a custom re-order could be useful.

Work-around is to remove all and recreate all in right order.
Or export, edit and import.
But would be safer through the extension GUI itself.

**Comment by dhruv-choudary** [comment]
I see this as must have feature. We will start working on this right away. 

Thank you for your suggestion @PerryFromHolland

**Comment by dharmesh-hemaram** [comment]
Hi @PerryFromHolland ,

We have developed the above feature and made it available on [DEV v3.1.9](https://chrome.google.com/webstore/detail/auto-clicker-autofill-dev/cpjikgcdmhfnmaiibplplldlchbjejel)


<img width="1142" alt="Screenshot 2021-01-25 at 3 03 48 PM" src="https://user-images.githubusercontent.com/2290202/105687671-bc6f4b00-5f1e-11eb-964e-441844e7df67.png">
<img width="813" alt="Screenshot 2021-01-25 at 3 03 56 PM" src="https://user-images.githubusercontent.com/2290202/105687667-baa58780-5f1e-11eb-8560-a4304f1911ac.png">
