### ISSUE TITLE
Enabled and Disabled Configuration mix-up prevention 

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#144]
It is very nice disabled Configuration still can be viewed since 3.1.5
Only now it's not very clear anymore what Configuration is Enabled and which not.
If I watch closely I see some text changing from Blue to Grey, but this is not very obvious to notice instantly. 

It would be nice disabled Configurations fully have a different color text or background/borders.
Or have a big sign in screen saying DISABLED.
Now it's really easy to overlook/forget

**Comment by tksoh** [comment]
I plead guilty to my suggestion on adding this feature :-P

I think setting the different background color on at least the banner that holds the enable button is much clearer indication than just the banner headers.

**Comment by dhruv-choudary** [comment]
We are very thankful to have good users like you (@tksoh & @PerryFromHolland).  

> We always appreciate suggestion of our users. We will come up with better solution which will resolve both of your issue. As we are good developer and not good designer so it takes so many trial and error before we end up into good design which is simpler to use for new users and have better features for advance users.

**Comment by dharmesh-hemaram** [comment]
Hi @tksoh & @PerryFromHolland ,

We have updated the UI of the configuration to highlight the disabled one. Please check and let us know.

<img width="1139" alt="Screenshot 2021-01-25 at 2 52 29 PM" src="https://user-images.githubusercontent.com/2290202/105687377-63071c00-5f1e-11eb-8c0b-c315bc63b2d2.png">
