### ISSUE TITLE
Use some Configuration as Template for a new one

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#145]
It would be useful a Configuration could be fully copied, initially named "COPY OF <configuration name> "

After very easy to create a tester Configuration this way and keep the original untouched.

**Comment by dhruv-choudary** [comment]
Great suggestion @PerryFromHolland , 

> We will look into this and try to bring changes. Currently we are struggling with design where we can keep UI simple and easy to understand and provide more feature. as we keep on add new features into extension. new users feel difficult to understand and end up providing bad reviews. so allow us sometime until we figure out some good way to bring this feature without increasing complexity for new users.

**Comment by Dhruv-Tech-Apps** [comment]
A duplicate configuration option is available now https://getautoclicker.com/docs/3.x/configuration/duplicate/
