### ISSUE TITLE
Random time with part of second possibility

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#148]
I would like running random repeats below 1s or for example between 0.5 and 2.5s.
AutoClick doesn't accept 0.2e0.8 or 0.5e2.5
Please can you change this? Also for init-waits

**Comment by dharmesh-hemaram** [comment]
Hi @PerryFromHolland ,

We have fixed above issue and made with available on [DEV v3.1.9](https://chrome.google.com/webstore/detail/auto-clicker-autofill-dev/cpjikgcdmhfnmaiibplplldlchbjejel)
