### ISSUE TITLE
Element found opens URL

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#149]
Would like the possibility to put an URL in the Value field to be opened immediately by AutoClicker when a certain Element is found

**Comment by dharmesh-hemaram** [comment]
Its already available checkout 

https://getautoclicker.com/docs/3.1/action/value/#location-command

**Comment by PerryFromHolland** [comment]
Perfect, I really didn't know😊
AutoClicker is such a complete tool👍🏻
Thank you for your help!!
