### ISSUE TITLE
ExecCommand:: no longer work

### ISSUE THREAD

**Issue by lucasuk86** [Dhruv-Techapps/auto-click-auto-fill#152]
ExecCommands do not work. Cut, copy, delete, paste & selectAll don't work.

When command is used it is ignored.

 - OS: iOS
 - Browser: chrome
 - Version Version 88.0.4324.96 (Official Build) (x86_64)

**Comment by PerryFromHolland** [comment]
Still under development, see https://getautoclicker.com/docs/3.1/action/value/

**Comment by lucasuk86** [comment]
Yes thats correct. Dhruv wanted me to create a ticket so he can keep track of it :-)

**Comment by dharmesh-hemaram** [comment]
> Still under development, see https://getautoclicker.com/docs/3.1/action/value/
> 
> As far as I can recall it was working in earlier Auto-Clicker versions, but due to a scripting language update needs to redesigned.
> 
> @dharmesh-hemaram Am I right?
- - > 
> 

Yes @PerryFromHolland we need to reimplement those changes.

@lucasuk86 thank you creating ticket

**Comment by dharmesh-hemaram** [comment]
- [Copy](https://getautoclicker.com/docs/3.x/action/value/#copy)
- [Paste](https://getautoclicker.com/docs/3.x/action/value/#paste)

are now available on dev mode.
