### ISSUE TITLE
Firefox "Auto Clicker - AutoFill" extension isn't working: empty page on click

### ISSUE THREAD

**Issue by MurzNN** [Dhruv-Techapps/auto-click-auto-fill#159]
**Describe the bug**
I have installed "Auto Clicker - Auto Fill" from Mozilla Extensions repository here https://addons.mozilla.org/ru/firefox/addon/auto-clicker-autofill-beta/ - it successfully adds the icon to toolbar.

But the icon is greyed-out and on left-click it simply opens new tab with https://beta.getautoclicker.com/ website, and that's all. How can I fix this?

**Comment by dharmesh-hemaram** [comment]
Our extension needs some API to work properly and Firefox has deprecated the same and doesn't have a plan to provide an alternate API so we no longer supporting the Firefox version of our extension.

**Comment by MurzNN** [comment]
Thanks for information, can you also describe which API was used and now is deprecated?

**Comment by dharmesh-hemaram** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/externally_connectable
