### ISSUE TITLE
Notification when certain element is found or specific condition is met

### ISSUE THREAD

**Issue by caisamuels** [Dhruv-Techapps/auto-click-auto-fill#161]
### Add the ability to receive a notification when a certain element is found or a specific condition is met.

For example, I have a configuration that repeatedly checks for a string on a page. It works by searching for the string on the page, and if it is not found, then it tries again. It would be great if I could configure the action so that I receive a notification when that certain string is found on the page. I believe this could be very useful.

**Comment by dharmesh-hemaram** [comment]
Now you can get a notification when a configuration is completed. https://blog.getautoclicker.com/2021/06/auto-clicker-auto-fill-3.2.9/

If you feel still this don't solve your issue feel free to open issue again
