### ISSUE TITLE
Masterswitch to enable/disable AutoClicker

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#163]
For testing it would be nice to have a Masterswitch to disable AutoClicker completely, without going into Browser Extensions Management. When Masterswitch OFF you're sure AutocClicker doesn't do anything anymore, opening whatever website

**Comment by dharmesh-hemaram** [comment]
We already have a master switch in chrome://extensions/ page where you can easily disable or enable the whole extension

![image](https://user-images.githubusercontent.com/2290202/111871739-bf803800-89b1-11eb-8b41-9791998552ff.png)

**Comment by PerryFromHolland** [comment]
True, but did ask for an easy reachable one on https://dev.getautoclicker.com/ config page, not going into the extensions config page of Chrome. So not a very important feature because the same can be achieved through chrome extension settings, just a nice to have ;-)

**Comment by dharmesh-hemaram** [comment]
Hmmmm. Sure will think over it again :)
