### ISSUE TITLE
Add-on Value in element does not work

### ISSUE THREAD

**Issue by lucasuk86** [Dhruv-Techapps/auto-click-auto-fill#164]
Add on Value does not work

Extension will ignore what value is

 - OS: MacOS 10.13.16
 - Browser: chrome
 - Version: 89.0.4389.82

**Comment by dharmesh-hemaram** [comment]
Hi @lucasuk86 ,

Can you please provide more information on same?

**Comment by lucasuk86** [comment]
This was fixed on the latest DEV update. You can close this now :-)

**Comment by dharmesh-hemaram** [comment]
@lucasuk86  thank you
