### ISSUE TITLE
Bigger Element Finder field

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#166]
Would like to have a much bigger Element Finder Field because this field many times contains a very long text.
Lots of lines are starting same and only differ in the end.
The Value Field could be smaller to give extra space to the Element Finder Field and/or the total layout of the webpage could be wider, assuming all are using at least 1920 x ... resolution nowadays on whatever display device. There is a lot of space unused right/left in the GUI now.

Another thought is the possibility to make the Element field resizable with a simple mouse movement, but I think this could have impact on the speed of the extension. And I like speed above all other ;-)

**Comment by PerryFromHolland** [comment]
Great, perfect to use now!
Suggestion: Next to section Action also widen sections Configuration and Batch to make the UI look nicer

**Comment by dharmesh-hemaram** [comment]
new UI is out with a better look and  feel checkout 

http://dev.getautoclicker.com/
