### ISSUE TITLE
It repeat whole process even after I set 0 Repeat

### ISSUE THREAD

**Issue by pratik223** [Dhruv-Techapps/auto-click-auto-fill#167]
![Capture](https://user-images.githubusercontent.com/53678806/111873365-02440f00-89b6-11eb-91c0-df44febaa2ca.PNG)
I want to try search DRESS keyword on amazon automatically.
It work very well but the problem is it repeat whole process.
How can I stop this?

**Comment by dharmesh-hemaram** [comment]
Hi @pratik223 ,

Can you try on [DEV](https://dev.getautoclicker.com/) version and see. 
![image](https://user-images.githubusercontent.com/2290202/111960400-b60fe080-8b15-11eb-91e1-acc1cee5746e.png)
