### ISSUE TITLE
The page https://stable.getautoclicker.com/ opened on its own

### ISSUE THREAD

**Issue by Melanol** [Dhruv-Techapps/auto-click-auto-fill#168]
**Describe the bug**
I was just watching a Twitch stream when the page opened showing my password. What if I myself was streaming? What was that? An update?

**To Reproduce**
1. Do nothing.

**Expected behavior**
None.

**Desktop:**
 - OS: Windows 7 
 - Browser: Chrome
 - Version: 89.0.4389.90

**Comment by dharmesh-hemaram** [comment]
Hi @Melanol ,

We release all new great features to the stable version today. the previous version was `2.2.0` and the latest new version is `3.2.0`

Please check out https://discordapp.com/channels/702091948902711388/804933573395087361/827067072039092234

![image](https://user-images.githubusercontent.com/2290202/113261896-a3539380-92ed-11eb-9261-9856bd69e972.png)

> I would keep this ticket open for some time if users have same issue
