### ISSUE TITLE
No longer working in chrome

### ISSUE THREAD

**Issue by diversc** [Dhruv-Techapps/auto-click-auto-fill#169]
The extension stopped working today. I tried to delete and reinstall but that didn't correct it.

**Comment by Thor496** [comment]
Not working in chrome.  "Error"
![Sem título](https://user-images.githubusercontent.com/81800239/113394218-be76df80-938f-11eb-8a43-43f5e8305c94.png)

**Comment by dharmesh-hemaram** [comment]
@diversc , @Thor496 ,

Can you please provide more info like on what site its throwing error and  on what action

**Comment by Nephin** [comment]
For me it stopped working on my Android device in Kiwi browser. It used to work perfectly until the update. It's still perfect on Windows/Chrome with the site I'm using, but mobile Kiwi shows only the velvet icon. meaning "connected and enabled" but no action is executed and no notification pops up (after enabling them). All configuration remained the same but it stopped working.

**Comment by dharmesh-hemaram** [comment]
@Nephin ,

We have made few fixes in new version. Can you please check again if your issues are solved

**Comment by Nephin** [comment]
Thank you @dharmesh-hemaram for your assistance. Unfortunately, it did not help. Still it is working on PC/Chrome/Windows10 but doesn't work on tablet/Kiwi/Android 4.4.2 and phone/Kiwi/Android 10.
It even got worse, now I can't access the configuration page. https://stable.getautoclicker.com/ is blank on two of these devices (PC and Android). Only my tablet with old Android shows the settings correctly and v3.2.1 (but does nothing anyway – does not perform any action despite the button turning velvet and no notification is shown despite turning them on).

**Comment by Nephin** [comment]
Now I have access to the settings page again, but it still doesn't work on mobile.

**Comment by dharmesh-hemaram** [comment]
@Nephin ,

It's working for a few of our users. If you are still facing the issue. we can have a screen share and discuss the same on [Discord](https://discord.gg/hArVQns).
