### ISSUE TITLE
I want click on a repetitive button in a website

### ISSUE THREAD

**Issue by carolinaz-merzigo** [Dhruv-Techapps/auto-click-auto-fill#171]
I translate 
![Captura de Pantalla 2021-04-03 a la(s) 8 26 40 a  m](https://user-images.githubusercontent.com/77626843/113469468-54753d80-9456-11eb-9ba3-858ed489142d.png)
And as you can see there are may "Request Machine Translation" I cannot set the extension to make the click on those bottom consecutively and finish the whole file, because manually it takes lots of time.
![Captura de Pantalla 2021-04-03 a la(s) 8 28 28 a  m](https://user-images.githubusercontent.com/77626843/113469493-943c2500-9456-11eb-8389-02d15f4c212d.png)

**Comment by dharmesh-hemaram** [comment]
Hi @carolinaz-merzigo,

Please drop message on our discord channel for configuration query https://discord.com/invite/hArVQns
