### ISSUE TITLE
stable.getautoclicker.com returning blank page

### ISSUE THREAD

**Issue by Malvenue** [Dhruv-Techapps/auto-click-auto-fill#172]
After clearing cookies, reinstalling the app stable.getautoclicker.com only returns a blank page.  When I initially installed the addon this morning, the page loaded fine but once I started creating a new configuration, the page went blank and has stayed blank since.  This is on 

Google Chrome | 88.0.4324.190 (Official Build) (32-bit)
-- | --
Revision | 3a97857a62ee2a8b3f6561ccd98b9e0436604cbe-refs/branch-heads/4324_182@{#3}
OS | Windows 10 OS Version 2009 (Build 19042.870)

**Comment by dhruv-choudary** [comment]
Hi @Malvenue ,

Thank you for writing down this issue. It was a cache issue from cloud server. We just cleared same.

Can you please retry now and see.

**Comment by Malvenue** [comment]
The issue has been resolved. Thank you.
    On Saturday, April 3, 2021, 09:35:17 AM CDT, dhruv-choudary ***@***.***> wrote:  
 
 


Hi @Malvenue ,

Thank you for writing down this issue. It was a cache issue from cloud server. We just cleared same.

Can you please retry now and see.
