### ISSUE TITLE
Possibility to use wildcards in URLS

### ISSUE THREAD

**Issue by Kuchiriel** [Dhruv-Techapps/auto-click-auto-fill#173]
Example:
https://website/point/CreatePoint?calendarId=172

This number 172 may vary and the extension wont match the correct URL.

Would be nice if it was possible to do something like:
https://website/point/CreatePoint?calendarId=*

(:

**Comment by PerryFromHolland** [comment]
Use https://website/point/CreatePoint?calendarId=

**Comment by deconline** [comment]
> Also Wildcards are possible to use, see https://getautoclicker.com/docs/3.x/configuration/url/

For me didn’ works the examples only the full urls :(
