### ISSUE TITLE
Export/import single configuration

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#175]
Possibility to not only export/import all configurations, but also for just one configuration

**Comment by PerryFromHolland** [comment]
Would be easy to share configs this way 😀

**Comment by dharmesh-hemaram** [comment]
It's already available under configure options.

![image](https://user-images.githubusercontent.com/2290202/115437160-77ab3580-a229-11eb-90d6-3218a4907efe.png)
