### ISSUE TITLE
Sync configuration with cloud

### ISSUE THREAD

**Issue by haobinliang** [Dhruv-Techapps/auto-click-auto-fill#176]
It would be nice if the configurations can be scynronised through cloud so it doesn't need to be export/import when using on a new device...

**Comment by PerryFromHolland** [comment]
Nice thought but could also be a security issue.
Best is to have sensitive info in the Configurations only on your device, not in the Cloud.
But general AutoClicker settings could be in the Cloud to sync over devices, agree
