### ISSUE TITLE
chrome://downloads/ Auto-Click

### ISSUE THREAD

**Issue by kingkarl2** [Dhruv-Techapps/auto-click-auto-fill#177]
I would like to have the extension automatically click "Resume" Download when a download stops due to network error or automatic shutdown (some sites limit bandwidth etc). However, when I enter URL as **chrome://downloads/** and the Resume button shows, nothing happens :( What am I doing wrong or does the extension not work?

I use the ElementFinder **//*[@id="pauseOrResume"]** and Value: **Click**

Everything is saved and configuration is enabled, so it should work.... I also tried using ElementFinder as **//button[contains(@class,'Resume')]** since the button can either be Pause or Resume, but I only want to resume once stopped, not Pause the download. But nothing worked; the Resume button wouldn't be clicked automatically.

Does anyone have a solution?? Thanks

Using Chrome Version 88.0.4324.96 (Official Build) (x86_64) on MacOsX

**Comment by dharmesh-hemaram** [comment]
But extension stop as soon as all its actions are completed. It doesn't watch on-page for any changes.
