### ISSUE TITLE
Notify feature request

### ISSUE THREAD

**Issue by mehdibahrami** [Dhruv-Techapps/auto-click-auto-fill#187]
Please add an ability to find a specific xPath after each click and notify the user if the target xPath is located on the page, and stop clicking after that.

**Comment by Dhruv-Tech-Apps** [comment]
You can use [dicord ](https://getautoclicker.com/docs/3.x/settings/show-notification/)notification to get notifications on your device.
You can use an [addon ](https://getautoclicker.com/docs/3.x/addon/overview/)to configure it in such a way that if it found any particular element on the page stop/process/skip actions.
