### ISSUE TITLE
Can't use multiple configs on one page

### ISSUE THREAD

**Issue by n0eL1405** [Dhruv-Techapps/auto-click-auto-fill#197]
**Describe the bug**
I have multiple configs for one page (to be more detailed on a Swagger page). The first one will be executed automatically when the page is loaded to authorize me. The second one will be executed with a hotkey (Ctrl + Shift + X if necessary) and enter data to test REST requests. The automated one will be executed but I can't use the one with the hotkey. If I deactivate the automated one, the other one works. The config order doesn't seem to have an impact.

**To Reproduce**
1. Create a config to login and let it execute when the page is loaded
2. Create a config that will be executed with a hotkey
3. Load the page
4. the automated config will be executed
5. Try to execute the hotkey one
6. No data will be entered in the fields

**Expected behavior**
I want to have multiple configs with different hotkeys for the page to test with different data.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version 94.0.4606.71 (64-Bit)

*EDIT:*
The config order has an impact: The one on top/above the other one works.

**Comment by dhruv-choudary** [comment]
Can you share some demo configuration

**Comment by NoelTheN00B** [comment]
> Can you share some demo configuration

login config: https://pastebin.com/EvmkR6bA
data config: https://pastebin.com/KZkhEjM3

I use `http://swagger.*.paradise.bsz-rancher.hup.intern/swaggerui/swagger-ui/*` in the automated login config as I need the login informations on multiple Swagger with this URL scheme, this URL woks fine. Full URL is `http://swagger.p5sdzt1.paradise.bsz-rancher.hup.intern/swaggerui/swagger-ui/index.html?configUrl=/swaggerui/swagger-config.json&urls=&url=http://censored-ip/logistic/calendar/v3/api-docs`

The IP is in both configs the same.

**Comment by kilik128** [comment]
not sure understand how i can use same config in another tab ?

**Comment by Dhruv-Tech-Apps** [comment]
> nderstand how i can use same config in another tab ?

You can use regular expressions in URLs to match multiple configurations at once. https://getautoclicker.com/docs/3.x/configuration/url/
