### ISSUE TITLE
Green button and this

### ISSUE THREAD

**Issue by Runizag1** [Dhruv-Techapps/auto-click-auto-fill#199]
Windows 10 . chrome last version
if i make the window small . its green button bothers me
![chrome_9oU67rBewx](https://user-images.githubusercontent.com/92772853/137842961-94563243-90f6-4c6b-bded-07991ca54bda.png)
and this top panel jumping
https://user-images.githubusercontent.com/92772853/137842986-59bffbc7-cfab-4734-a9a8-cce08250ec25.mp4

**Comment by dharmesh-hemaram** [comment]
This is fixed
