### ISSUE TITLE
the page that tells you to get rid of your add blocker shows even when i have the extension turned off 

### ISSUE THREAD

**Issue by jarroldpinnsery** [Dhruv-Techapps/auto-click-auto-fill#205]
**Describe the bug**
the page that tells you to get rid of your add blocker shows even when I have the extension turned off 

**To Reproduce**
1. Go to 'the auto clicker website'
2. See error

**Expected behavior**
It should go away 

**Screenshots**
I would but I have no clue how

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by dharmesh-hemaram** [comment]
We have tested this well and unable to reproduce the issue. Can you provide more information on this
