### ISSUE TITLE
Feature Requested

### ISSUE THREAD

**Issue by Likhithsai2580** [Dhruv-Techapps/auto-click-auto-fill#206]
PLEASE ADD MATHS OPEERATION +-/* IN DATA

**Comment by dharmesh-hemaram** [comment]
Currently our Extension structure is like for single url there are many action and each Action there is one Element and Value (process). Now to perform mathematics operation it require minimum two value so . In total it will require three element. two from where to copy numbers which need to operate and third element where to put result. So this is not easily adjusting in our extension. So if there is any specific site where you require such operation we can help you create separate extension for same
