### ISSUE TITLE
Choice option REC mode

### ISSUE THREAD

**Issue by PerryFromHolland** [Dhruv-Techapps/auto-click-auto-fill#208]
In the DEV version is a record mode option now when using the right mouse click on a webpage. I would like to have an option in settings to activate Record mode or (the old) Right Click mode. Personally I don't like the Rec mode so this way can choose which mode to use. 

Other option is to add a second option to the mouse right click.
One for Record and one restoring the old adding to a configuration.

**Comment by PerryFromHolland** [comment]
Just noticed if you're using Record mode, when you click a button and the page moves to another page the "Record Stop" button is gone and the Configuration is created empty (existing Configurations missing the new recorded clicks). Recording might be a good idea for lots of clicks on just one page, but really missing the normal Right Click function...

**Comment by dharmesh-hemaram** [comment]
Both version are available now.
