### ISSUE TITLE
Problem with random values like 10e30

### ISSUE THREAD

**Issue by chshkhr** [Dhruv-Techapps/auto-click-auto-fill#210]
**Describe the bug**
The values like 10e30 are interpreted as numbers in scientific format after reopening the browser :
10e30 -> 1e+31
1e5 -> 10000

**To Reproduce**
Close and then open the browser

**Expected behavior**
The values must be unchanged after reopening the browser

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - All available versions of AutoClicker

**Comment by chshkhr** [comment]
By the way, if you enter f.i. **10E30** instead of **10e30** you will see how the values are transformed after reloading on the browser restart

**Comment by dharmesh-hemaram** [comment]
Hi @chshkhr ,

Can you provide more information like in which field you are getting this error . screen shot would help better

**Comment by chshkhr** [comment]
Hi @dharmesh-hemaram, 
This error happens in any numeric field. If the first value (before **e**) is not multiple of ten and if the second value (after **e**) is rather big (12 or more) the problem will not appear. F.i. if instead of **10e20** you'll use **9e20** then it will be saved and then restored without the problem. It's obvious that such values transfer on save/restore to the **scientific e notation** [link](https://www.calculatorsoup.com/calculators/math/scientific-notation-converter.php) 

Here are two screenshots:

1. 
![1](https://user-images.githubusercontent.com/10610759/149365489-ffcdf080-00f4-4322-bede-99f1fa69747f.png)
2.
![2](https://user-images.githubusercontent.com/10610759/149365496-5feb23b2-7487-4cc9-b91f-06f1c721c0c1.png)

**Comment by dharmesh-hemaram** [comment]
This issue is resolved with the latest release of the configuration page. If you still face issues. Just do hard refresh or open developer console -> Application -> Storage and clear site data.

![image](https://user-images.githubusercontent.com/2290202/153212074-eb8b13ad-2f1d-42da-aab3-5724cd420143.png)

**Comment by chshkhr** [comment]
Cool! Thanks!
