### ISSUE TITLE
how to solve this input type？

### ISSUE THREAD

**Issue by daerdai** [Dhruv-Techapps/auto-click-auto-fill#211]
![image](https://user-images.githubusercontent.com/11593437/149260430-2a8f86fc-27d2-4b09-88d1-bd869adc529f.png)
![image](https://user-images.githubusercontent.com/11593437/149260503-43c7a566-3ba7-4fed-a5fd-b75d69f46958.png)
not work！

**Comment by dharmesh-hemaram** [comment]
Its a custom dropdown. You need to create two actions for this. One to open dropdown and second action to select a value.

We are more active on discord please connect here https://discord.com/invite/ubMBeX3

**Comment by dharmesh-hemaram** [comment]
Closing this ticket as no respone
