### ISSUE TITLE
new feature for addon

### ISSUE THREAD

**Issue by bruasr1** [Dhruv-Techapps/auto-click-auto-fill#212]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to add "length of string" to **conditions** drop-down menu in Addon settings

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/97888604/149768520-bf633a40-6e0f-4c7f-96d7-5d0d5b36e639.png)

**Comment by dharmesh-hemaram** [comment]
Now you can add Addon condition to compare length of string also . Under Value you need to add regex which can match the length of value which you trying to compare.

Example If you want to check the length of input field value.

Add Addon
Element Finder - point to the input field whose value need to compare.
Condition - Equal 
Value - `.{3,}` - here 3 is for minimum or start range. If you want to check the length exact three remove the ,

`[a-z]{3}` - pass if the value is three characters and all three alphabets in small case
`[A-Z]{3}` - pass if value is three characters and all three alphabets in small case
`[A-z]{3}` - pass if value is three characters and all three alphabets
`.` - compares everything
`\d` - to compare the number
