### ISSUE TITLE
Values like Random::[a-z]{6} not working in DEV

### ISSUE THREAD

**Issue by chshkhr** [Dhruv-Techapps/auto-click-auto-fill#217]
Values like Random::[a-z]{6} not working in DEV https://getautoclicker.com/docs/3.x/action/value/#random-value

**Comment by dharmesh-hemaram** [comment]
Updated docs for a random number. Follow updated syntax for random
```
<random::[A-Z]{6}>
```

https://getautoclicker.com/docs/3.x/assets/img/action-random.png

**Comment by chshkhr** [comment]
Thanks!

**Comment by chshkhr** [comment]
That is right <random[A-Z]{6}>
