### ISSUE TITLE
Sometimes "wait" work not right and waits exactly 1 Minute instead of time that was setup

### ISSUE THREAD

**Issue by nXwhite** [Dhruv-Techapps/auto-click-auto-fill#219]
At first i want to say, i really love this extension!! Its awesome! Thanks a lot for it! :)
And its my first post here on github. So i hope i´ll do everything right... 
i´ve already searched for this kind of bug, but didnt find anything. But i want not believe that i´m the only one who have it. Because its appearing on two differend machines. 
Allright lets go:

**Describe the bug**
I´ve set up a configuration, with inifinty batch repeats and 5 actions in it. Some of the actions have also additional action-settings. But nothing complicated. Only things like: retry 4 times with 1 second waiting between. 
And its running smooth the most of the time. But sometimes it beginns to wait for exactly 1 Minute. It repairs itself most times after the batch-repeat. But not everytime! I will include a Screenshot where you can see that the protocol says "wait XX sec" but the next timestamp is 1 minute later. In some rare cases its not exactly 1 minute... but still much longer then the chosen time. 
I also have the feeling it appears more offten if the Tab where the config is running isnt the active tab. But it also appears when the Tab is activ. So i´m not sure, if this really a reason.

**To Reproduce**
I´m not sure if its reproducable but maybe try:

Set up a config with infinite batch repeats. Put in some actions with a few action-settings. And let it run for some hours. 

**Expected behavior**
Also not sure what to say here. But i guess i´ve expected that the wait-command does always the same^^

**Screenshots**

![2022-02-18 (2)](https://user-images.githubusercontent.com/89658180/154732439-a53d83b5-acd9-45ab-9839-09bc0b9d400b.png)

**Desktop (please complete the following information):**
Both machines running:
 - OS: [win 10]
 - Browser [brave]
 - Version [v 1.35.103]

**Additional context**
For me it looks like that the extension struggles sometimes with the wait-command. 
In my Sceenshot you can see that the first 5 Lines worked well. Then it beganns to do the things wrong for the rest of the Lines. And as you maybe also can see, the same 5 Lines that worked right in the beginning didnt work right no more at the end. unfortunately the screenshot shows not that everything was normal again, after the last Line.

I wish i could tell you more details. but i dont know what would also be important. So please tell me, if you need more! I want to help! 

Thanks and have a nice day!

**Comment by dharmesh-hemaram** [comment]
I see that in the log you are getting a time difference. we tried out on our test page with different scenarios but all ran successfully.

Can you provide more information on this like so we can think over it. is It something like you keep the browser minimissed and also what OS you are using.

**Comment by dharmesh-hemaram** [comment]
Closing as not ablee to reproduce and no input from user. 

Do reopen this ticket to provide additional information

**Comment by nXwhite** [comment]
i'm sorry! The first days after i wrote my question i have logged in every day, hopping for an answer. But after one week without an answer i was in the opinion i dont will get one... So i didnt realize that you have answered a few days later. 
Sorry for not responding!

Of course i would provide the missing informations! But it looks like you have already fixed this issue, because for the last weeks the bug has not appeared anymore :)

Thanks a lot! :)
