### ISSUE TITLE
refresh rate for xpath not found

### ISSUE THREAD

**Issue by MaxProfesor** [Dhruv-Techapps/auto-click-auto-fill#222]
An option to set refresh rate when xPath is not found. Under "action settings" you can choose to refresh when xpath is not found, its a useful feature although not being able to choose how often you want to refresh the page reduces its utility to very little amount of applications.

**Comment by Dhruv-Tech-Apps** [comment]
It's already available https://getautoclicker.com/docs/3.x/action-settings/retry/
