### ISSUE TITLE
Func::Date().getHours()

### ISSUE THREAD

**Issue by romikkazan** [Dhruv-Techapps/auto-click-auto-fill#223]
Func::Date().getHours() - It works only in the development version, and causes an error in beta and stable versions.

Even in the development version, whatever condition, it never triggers at 0 hours. In other words: whole hour, from 0 to 1 night, the action will never be executed. Whatever condition is indicated - it will be missed. 0 hours is always processed incorrectly.

**Comment by dharmesh-hemaram** [comment]
This issue is fixed and deployed
