### ISSUE TITLE
Append text in <textarea>

### ISSUE THREAD

**Issue by VulcanRebel** [Dhruv-Techapps/auto-click-auto-fill#224]
Was hoping for a way to add/paste text and not replace the current text in a textarea or any input field. 
For example: 
<textarea>Variables</textarea>
- now add initials - 
<textarea>Variables - VR 3/4/22</textarea>. 
Currently it replaces all text in the field resulting in:
<textarea>- VR 3/4/22</textarea>

**Comment by VulcanRebel** [comment]
Ran into a bug with this. Prepend:: is adding value twice sometimes. 

Example in textarea:
Prepend::RM 3/25/2022
Results in textarea:
RM 3/25/2022RM 3/25/2022

Was working fine all day. Just randomly started happening.

**Comment by dharmesh-hemaram** [comment]
New feature added in DEV version
