### ISSUE TITLE
To apply a configuration on the list of pages (predefined and fetched by action)

### ISSUE THREAD

**Issue by exactstat** [Dhruv-Techapps/auto-click-auto-fill#226]
**Case 1: a list of pages is predefined by a user**
A user creates a list of URLs for the particular configuration. Configuration can be applied on each URL one by one automatically.

**Case 2: a list of pages is fetched from an action.**
It's a bit harder, but I have a proposition on how to implement it, just as an option.
Configuration must have variables that can be set. Also, action results can be passed to the configuration variable.
Special action is required to run a configuration with variables set externally.
So,
(some myconfig predefined and uses the `work_link` variable to open a page)
Action 1: variable `links_array` = xpath //a
Action 2: run myconfig with `work_link=links_array[i]` (for each value in the array)
Action 3: ... any other actions after loop complete.

**Comment by dharmesh-hemaram** [comment]
Hi @exactstat ,

This looks altogether like a new requirement and not as an enhancement. We are not developing new extension
