### ISSUE TITLE
WindowCommand::paste not work

### ISSUE THREAD

**Issue by xFanly** [Dhruv-Techapps/auto-click-auto-fill#229]
WindowCommand::paste not work

Chrome、Windows 10

**Comment by nXwhite** [comment]
Is it so hard to write a bit more and not just whats not working?

All these Points: "**Describe the bug** **To Reproduce** **Expected behavior**" are not there just for fun! 
Nobody can help, if you not provide all nessesary informations!

**Comment by Dhruv-Tech-Apps** [comment]
There used to be an experimental clipboard API in Chrome, but this was removed in Chrome 13.

https://stackoverflow.com/questions/6969403/why-is-document-execcommandpaste-not-working-in-google-chrome

we also don't support both windowCommand::copy and paste. removed from the document section as well.
