### ISSUE TITLE
I am just looking for an extension that auto-clicks the left mouse button repeatedly over wherever I take the mouse cursor on my screen.  The set up tutorial isn't very clear on this.  Also, would need to set a hot key to active it.  How is it done?  This is for the Edge extension.

### ISSUE THREAD

**Issue by Vostik1** [Dhruv-Techapps/auto-click-auto-fill#232]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nXwhite** [comment]
To aswer your hotkey-question:
In the same line, where you turn your configuration on and off are 3 dots on the right side. press it and click on "cofiguration settings". There you can choose if config should start automatic or manual. If you choose "manual" you can set the Hotkeys you want!

**Comment by Dhruv-Tech-Apps** [comment]
Hi @Vostik1 ,

Our extension dont work that way. it click on elements which you define in configuration and does not follow mouse pointer.

more on how extension work checkout out discussion https://github.com/Dhruv-Techapps/auto-click-auto-fill/discussions/257
