### ISSUE TITLE
Action Settings > Retry > -2 does not work

### ISSUE THREAD

**Issue by Gabriele-LS** [Dhruv-Techapps/auto-click-auto-fill#233]
Hello! It looks like using -2 in **Action Settings** > **Retry** creates issues. If I put that value in that field and I close and reopen the **Action Settings** window, I find -2 also in the **Retry Interval** field. Moreover, that entire feature does not work as expected. Please note that everything works fine if I put 999 in the **Retry** field and 10 in the **Retry Interval**.

**Comment by Dhruv-Tech-Apps** [comment]
This issue is fixed.
