### ISSUE TITLE
ScrollToEvents >> start window.scrollTo(t, a) not working

### ISSUE THREAD

**Issue by ryshin-commerce** [Dhruv-Techapps/auto-click-auto-fill#235]
A few sites  use css to hide scroll bar window.scroll [ScrollTo::BottomRight] does not work. is it possible to create (ScrollTo::ScrollIntoView) ELEMENT.scrollIntoView() to solve this problem?

**Desktop (please complete the following information):**
 - OS:[Windows 10]
 - Browser [chrome]
 - Version [103.0.5060.134]

**Comment by Dhruv-Tech-Apps** [comment]
https://getautoclicker.com/docs/3.x/action/value/#scroll-to



ScrollTo:: | Description
-- | --
ScrollTo::XPath | It will scroll the page to element.
