### ISSUE TITLE
Diverse Urls didn’t work With .* 

### ISSUE THREAD

**Issue by deconline** [Dhruv-Techapps/auto-click-auto-fill#239]
The urls for EX https://myurl.com/admin_order.php?key=12345 
The actions works only if we give the complete url. If we give only https://myurl.com/admin_order.php?.*
The action don’t work. 
Is there a was to solving this problem?

**Comment by Dhruv-Tech-Apps** [comment]
Please checkout out below discussion:

https://github.com/Dhruv-Techapps/auto-click-auto-fill/discussions/201

https://github.com/Dhruv-Techapps/auto-click-auto-fill/discussions/256

Try out : `https://myurl.com/admin_order.php?key`
