### ISSUE TITLE
retry, retry interval(sec) are not independent

### ISSUE THREAD

**Issue by programmerahul** [Dhruv-Techapps/auto-click-auto-fill#240]
**Describe the bug**
click on action setting
fill retry 5 
fill retry interval 10

**Expected behavior**
retry=5
retry interval=10

before
**Screenshots**
<img width="604" alt="image" src="https://user-images.githubusercontent.com/84563516/183237771-996ad2d6-d2d5-4250-a043-ab33202daebf.png">

after :10 10
<img width="597" alt="image" src="https://user-images.githubusercontent.com/84563516/183237794-537eda72-82d7-4f44-9a95-c11a505c0483.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Dhruv-Tech-Apps** [comment]
This issue is fixed.
