### ISSUE TITLE
Cant find the button ID

### ISSUE THREAD

**Issue by rt400** [Dhruv-Techapps/auto-click-auto-fill#245]
I have website that start with "Click to Start" but i cant found how to make the AutoClick work with it.

I catch the html file and I can see that he run on script.

`<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>ticktac</title>

    <script>
            var urlParams = new URLSearchParams(window.location.search);
        if (!urlParams.get('local')) {
            var zon = false;
            var zns = false;
        }
    </script>

    <script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
    <script src="js/lib/createjs.js"></script>
    <script src="js/lib/zim_min.js"></script>
    <script src="js/lib/sweetalert2.js"></script>
    <script src="js/lib/axios.min.js"></script>
    <script src="js/lib/hebcal.min.js"></script>
    <script src="js/lib/game_2.6.js"></script>

    <script src="js/helper/Functions.js?v=25"></script>
    <script src="js/helper/Builder.js"></script>
    <script src="js/helper/ObjectView.js"></script>
    <script src="js/helper/GetStationDetails.js"></script>

    <script src="js/App.js?v=25"></script>
    <script src="js/Main.js?v=25"></script>
    <script src="js/Data.js?v=25"></script>
    <script src="js/Server.js?v=25"></script>
    <script src="js/MediaView.js?v=25"></script>

    <script src="js/compenents/Gallery.js?v=25"></script>
    <script src="js/compenents/Messages.js?v=25"></script>
    <script src="js/compenents/Flashes.js?v=25"></script>
    <script src="js/compenents/Birthday.js?v=25"></script>
    <script src="js/compenents/Clock.js?v=25"></script>

    <script>
            let stage;
            let startBtn = false;
            let displayMp4Vid = false;
            let showAlerts = true;
            let messageAlert = "";
        var mainAssets, main, onDevice;
            var meter;
            var showMeter = true;
            var logo;
            var frame = new Frame({ scaling: FIT, width: 1280, height: 720, color: "#ffffff", outerColor: dark, ready: ready, assets: ["assets/logoBig.png"], rollover: false });
        function ready() {
            MOBILE = true;
            stage = frame.stage;
            var params = getQueryString();
            var details = {};
            loop(params, (key, value) => {
                details[key.toLowerCase()] = value;
            })
            var skipBtn = false;
            if (details.skipbtn) skipBtn = true;
            if (details.symbolid) localStorage.symbolID = details.symbolid;
            if (details.screenid) localStorage.screenID = details.screenid;

            Ticker.setFPS(30, 60)
            Ticker.always();

            if (showAlerts && !window.navigator.onLine) {
                errorAlert("שגיאה בחיבור לאינטרנט");
                return
            }

            if (location.host == "localhost") {
                onDevice = true;
            }

            document.addEventListener("deviceready", onDeviceReady, false);
            function onDeviceReady() {
                if (window.KeepAwake) KeepAwake.start();
                cordova.plugins.autoStart.enable();
                onDevice = true;
            }

            logo = asset("assets/logoBig.png");
            logo.sca(0.3).centerReg().mov(0, -130)

            if (showAlerts) {
                messageAlert = new Label({ size: 40, text: "האפליקציה עולה", align: "center" });
                messageAlert.pos(0, 30, "center", "bottom");
            }

            // localStorage.symbolID = 611541;
            // localStorage.screenID = 5624;

            if (!(localStorage.screenID && localStorage.symbolID)) {
                getDetails(() => { new App(); })
                return
            }

            if (onDevice) skipBtn = true;

            if (details.local || skipBtn) new App();
            else if (localStorage.autoReload) {
                delete localStorage.autoReload;
                // setTimeout(() => { closeFullscreen(); }, 4000);
                // setTimeout(() => { openFullscreen(); }, 8000);
                new App();
            }
            else {
                startBtn = new Rectangle({ width: 180, height: 50, color: "purple", corner: 5 }).centerReg().mov(0, 20);
                new Label({ text: "הקש להתחלה", color: "#ffffff", size: 25 }).centerReg(startBtn);
                startBtn.on("mousedown", () => {
                    startBtn.dispose();
                    // if (checkBox) checkBox.dispose();
                    new App();
                    S.update();
                });

                // var checkBox = new CheckBox({ size: 30, label: "הצג ביצועים", rtl: true }).center().mov(0, 200).change(() => {
                //     showMeter = checkBox.checked;
                // });
            }

        }
    </script>
    
    <meta name="viewport" content="width=device-width, user-scalable=no" />
</head>
<script src="cordova.js"></script>

</html>
`
Screenshot from the website

![image](https://user-images.githubusercontent.com/38878996/197466392-a70f0c73-c808-4190-acb6-5c830a5bff09.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version latest

Thanks...

**Comment by Dhruv-Tech-Apps** [comment]
As this button is generated/created through script once the page is fully loaded

**Comment by rt400** [comment]
got it.
So is there a way to simulate clicking the button?

**Comment by dharmesh-hemaram** [comment]
Yes you need to inspect the html page and check what is button element tag . Inspection is different from view source

**Comment by rt400** [comment]
this is what i get in Inspect mode :
```<canvas id="myCanvas" tabindex="0" width="844" height="475" style="background-color: rgb(255, 255, 255); position: absolute; width: 563px; height: 316.687px; left: 0px; top: 126.156px;"></canvas>```

**Comment by rt400** [comment]
They change the html so the button are remove. I close this issue. thanks to all
