### ISSUE TITLE
Get paragraph inner text (p tag)

### ISSUE THREAD

**Issue by 4n0n1mo** [Dhruv-Techapps/auto-click-auto-fill#246]
How can I get a paragraph inner value?

HTML:
`<p style="spacing:4px" class="1.0 1.2 12 13">$300</p>`

I'm trying to get only $300 value, I've tried using in value extractor the value` /\$(\d*)/`, without success.
How can I debug and see what is coming from value extractor?

**Comment by dharmesh-hemaram** [comment]
under add-on are you trying to check this value again greater than or less than comparison. If so it will not work because adding $ to number will convert number into string and a string can't be compared with number.

**Comment by Dhruv-Tech-Apps** [comment]
Try value extractor as `/(\d+)/`
