### ISSUE TITLE
Microsoft Edge not save Configuration

### ISSUE THREAD

**Issue by kaiter999** [Dhruv-Techapps/auto-click-auto-fill#250]
Microsoft Edge not save Configuration when out browser Configuration will be delete.
Microsoft Edge version 107.0.1418.56

**Comment by Dhruv-Tech-Apps** [comment]
Which variant of extension DEV | BETA | STABLE?

Also have you tried by clearing cache and run

**Comment by kaiter999** [comment]
It happen in DEV | BETA | STABLE version

I try clearing cache and run but it not resolve !

**Comment by Dhruv-Tech-Apps** [comment]
Let us look into it

**Comment by Dhruv-Tech-Apps** [comment]
Hi @kaiter999 , 

we just tried on the dev version and we are able to save the configuration and it's working fine. 

We cleared our cloud cache. Can you try `Ctrl + Shift  + R` which is for hard refresh and try again?

**Comment by kaiter999** [comment]
with dev version import config Ctrl + Shift + R it normal but when exit browser and open edge it empty config

**Comment by Dhruv-Tech-Apps** [comment]
Hi @kaiter999 ,

We have fixed that issue on edge browser. Can you recheck and let us know if it works fine and its good to close this issue
