### ISSUE TITLE
Configuration not starting when another page takes me to the url

### ISSUE THREAD

**Issue by Aheilamper** [Dhruv-Techapps/auto-click-auto-fill#258]
**Describe the bug**
I have a configuration to start off a certain url. when I type the url in the search bar and click enter, it will work. or if i'm on the page and click refresh, the configuration will work. 

if i have a different page take me there. it will not work.

**To Reproduce**
1. I go to the different page (https://app.amper.xyz/#/login-outpost) and click the grey "back to regular log in"
2. nothing happens when i get back to https://app.amper.xyz/#/
3. if i refresh the page, it works

**Expected behavior**
i expect it to work if anything takes me to that page
if i go to https://app.amper.xyz/#/, it should click the "use code to log in" button - it does if i go straight to that page from the search bar or refresh it
if you click the "use code to log in" button, you'll see a link at the bottom in grey saying "back to regular log in"
if i click that, the autofill/autoclick does not work to take me back to that page

**Desktop (please complete the following information):**
 - Browser [chrome, ]

**Additional context**

**Comment by Dhruv-Tech-Apps** [comment]
Please checkout 
https://github.com/Dhruv-Techapps/auto-click-auto-fill/discussions/201
https://github.com/Dhruv-Techapps/auto-click-auto-fill/discussions/256
