### ISSUE TITLE
Chromium Raspberry Cannot read property 'configs' of null

### ISSUE THREAD

**Issue by rampfox** [Dhruv-Techapps/auto-click-auto-fill#272]
**Describe the bug**
Chromium on Raspberry Error Cannot read property 'configs' of null

**To Reproduce**
1. Go to getautoclicker page
2. See error

**Expected behavior**
work normally

**Screenshots**
![image](https://user-images.githubusercontent.com/36215916/217772070-4a84f19a-9eea-4a0c-87ff-f878f28a8e3b.png)

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS Buster
 - Browser: Chromium 
 - Version: Version 90.0.4430.212 (Developer Build) built on Debian 10.2, running on Debian 10.11 (32-bit) 

**Additional context**

**Comment by Dhruv-Tech-Apps** [comment]
Please update browser version
