### ISSUE TITLE
Bet365

### ISSUE THREAD

**Issue by Syr0** [Dhruv-Techapps/auto-click-auto-fill#276]
When loggin into bet365 there is a special security issues to bypass which cannot be done at the moment:
One of the following tricks could do so:
1) Change the context of the current JS (seems to be blocked by design from chrome)
2) Simulate input keys (seems to be impossible with JS)
3) Open custom urls - necessary anyway, could be used to call a custom protocol to make a program smash the return button

**Comment by Dhruv-Tech-Apps** [comment]
Can you provide url of site and also if it require login to access can you create dummy login credentials.

**Comment by Syr0** [comment]
URL: https://www.bet365.de/#/HO/
Username: test4autofill
Password: Tes4autofill!
![image](https://user-images.githubusercontent.com/6566797/218980526-d7c1b380-02dd-4051-a8a2-404fcbf74f55.png)

**Comment by Syr0** [comment]
I am interested on a diffrent button, but this one seems to work with the same technique. So the task is to click that button - somehow

**Comment by Dhruv-Tech-Apps** [comment]
Can you manually create configuration and try

URL - copy and paste of website.
Action
  - Element Finder : //*[contains(text(),"Identit")]
Value as blank.

Refresh page and check
*-----------------------------------------------------------------------------------------------*
*Docs: *Getting Started
<https://getautoclicker.com/docs/3.x/getting-started/introduction/> | Batch
<https://getautoclicker.com/docs/3.x/batch/overview/>| Action
<https://getautoclicker.com/docs/3.x/action/overview/>| Addon
<https://getautoclicker.com/docs/3.x/addon/overview/>| Settings
<https://getautoclicker.com/docs/3.x/settings/overview/>| Element Finder
<https://getautoclicker.com/docs/3.x/action/element-finder/>

Chat on Discord <https://discord.gg/vmnNfWKqnR>

Thanks and Regards,
Dhruv Techapps

**Comment by Syr0** [comment]
Nothing happens, It keeps "Retry", but nothing happens

**Comment by Syr0** [comment]
The problem with this thing is, that is runs in a diffrent context. It's a document in a document. And Chrome seems not to allow to interact with JS on site B while bein on Site A

**Comment by Syr0** [comment]
This will not work
![image](https://user-images.githubusercontent.com/6566797/218988945-53882a27-d1b7-4836-974f-136a152fbf7e.png)

**Comment by Syr0** [comment]
This will work
![image](https://user-images.githubusercontent.com/6566797/218989078-79b95adb-bea0-4ba8-a29d-94c2f35dc9c0.png)

**Comment by Syr0** [comment]
The correct context displayed here is": undefined (/memers.bet365.de/)"

**Comment by Syr0** [comment]
I dunno why the chrome console is allowed to switch context while plugins are not. 
I only found the following solutions:

- simulate 'tab' 'tab' 'return' key press
- Switch context somehow and simulate the click
- call an external program, connect to chrome and simulate the tab tab return. This could be done from inside the browse by predefining custom protocols in the windows registry but still needs a manual 'permission grant' within chrome which sucks cause the goal is to automate it completely

**Comment by Dhruv-Tech-Apps** [comment]
I tried with username password provided its not able to login
*-----------------------------------------------------------------------------------------------*
*Docs: *Getting Started
<https://getautoclicker.com/docs/3.x/getting-started/introduction/> | Batch
<https://getautoclicker.com/docs/3.x/batch/overview/>| Action
<https://getautoclicker.com/docs/3.x/action/overview/>| Addon
<https://getautoclicker.com/docs/3.x/addon/overview/>| Settings
<https://getautoclicker.com/docs/3.x/settings/overview/>| Element Finder
<https://getautoclicker.com/docs/3.x/action/element-finder/>

Chat on Discord <https://discord.gg/vmnNfWKqnR>

Thanks and Regards,
Dhruv Techapps

**Comment by Syr0** [comment]
![image](https://user-images.githubusercontent.com/6566797/219337839-d5657db7-8333-4f6f-bd7f-d42176c1dd3c.png)
This works for me
Ensure that:
1) No Proxy/ VPN is active since bet365 seems to blacklist those
2) The password is "Tes4autofill!", not "Test4autofill!" (the T is missing on purpose!)

**Comment by Dhruv-Tech-Apps** [comment]
Let me check once I’m on desk Sent from my iPhoneOn 16-Feb-2023, at 3:52 PM, Syr0 ***@***.***> wrote:﻿

This works for me
Ensure that:

No Proxy/ VPN is active since bet365 seems to blacklist those
The password is "Tes4autofill!", not "Test4autofill!" (the T is missing on purpose!)

**Comment by Dhruv-Tech-Apps** [comment]
Rename file .txt -> .json 

Import configuration and refresh page. It was because page is loaded within iframe.

[bet365 members (Verify Identity).txt](https://github.com/Dhruv-Techapps/auto-click-auto-fill/files/10763068/bet365.members.Verify.Identity.txt)

**Comment by Syr0** [comment]
Nice - than works. For documentation, I'll write the file as a string here: 
[{"name":"configuration-1","url":"","initWait":0,"startTime":"","enable":true,"startType":"auto","loadType":"window","hotkey":"Ctrl + Shift + A","batch":{"refresh":false,"repeat":0,"repeatInterval":0},"actions":[{"name":"","initWait":0,"elementFinder":"","value":"","repeat":0,"repeatInterval":0,"addon":{"elementFinder":"","value":"","condition":"","valueExtractor":"","recheck":0,"recheckInterval":0,"recheckOption":"stop"}}]},{"actions":[{"addon":{"condition":"","elementFinder":"","recheck":0,"recheckInterval":0,"recheckOption":"stop","value":"","valueExtractor":""},"elementFinder":"","initWait":0,"name":"","repeat":0,"repeatInterval":0,"value":""}],"batch":{"refresh":false,"repeat":0,"repeatInterval":0},"enable":true,"hotkey":"Ctrl + Shift + A","initWait":0,"loadType":"window","name":"","startTime":"","startType":"auto","url":""}]

The idea was just to use the iframe's URL right? - Can you implement that into the Locator? Cause now it looks pretty obvious. Thank you!
