### ISSUE TITLE
Value Extractor for all digit in one value 

### ISSUE THREAD

**Issue by betagoyal** [Dhruv-Techapps/auto-click-auto-fill#285]
I am here to request a new feature which extract all digit in one number from string .
Here is an example . 
String  "13-Feb-2023 [00:06:36]"
Value "132023000636"

**Comment by Dhruv-Tech-Apps** [comment]
13-Feb-2023 [00:06:36] -> 13`Feb`2023000636

**Comment by betagoyal** [comment]
i need only digit 132023000636
