### ISSUE TITLE
Ram Usage is going too high 

### ISSUE THREAD

**Issue by abdulmalek1971** [Dhruv-Techapps/auto-click-auto-fill#295]
I am having Hp pavilion gaming laptop with 8 gb ram . Normally my laptop’s ram usage is 28-40% but when I open Chrome and use autoclicker in (https://suvidha-mp.wb.gov.in/ ), after login in, my laptop’s ram usage hikes to 90-99% and chrome gets hang .

**Comment by Dhruv-Tech-Apps** [comment]
Can you check your configuration if you have used retry / recheck without interval value .

**Comment by Dhruv-Tech-Apps** [comment]
If possible do share configuration with us

**Comment by abdulmalek1971** [comment]
> Can you check your configuration if you have used retry / recheck without interval value .

yes I checked it was zero then i changed it to 0.1sec and now it is solved . Thanks to you for providing such a good extension free
