### ISSUE TITLE
Urgent - Selector not working for Iframe

### ISSUE THREAD

**Issue by gerardyadav** [Dhruv-Techapps/auto-click-auto-fill#297]
Hi,

I tried entering the around 7 Selecter Elements i.e. I frame to be clicked on but its showing me a red dot, from more action setting I selected "Iframe first" but that never helped, I also tried Selector All with Selector but that also never helped. I got the Selector Element by going to the inspector panel, right clicking and saying copy selecter, I love the interface of your platform and the ease of your product please help me, thank you.

**Comment by gerardyadav** [comment]
Hi please find my Adsterra codes below, please advice if except for Selecter can I use any other “Element Finder”, thank you

Added in the Head

Ad 1

<script type='text/javascript' src=‘//pl18677734.highrevenuegate.com/13/09/d0/1309d0b737bafe56cc10dd27dc1dedd2.js'></script>


All remaining codes are added in the Body

Ad 2

<script type="text/javascript">
	atOptions = {
		'key' : '04cb581b5b5d8ea1dfaea16b4704b721',
		'format' : 'iframe',
		'height' : 60,
		'width' : 468,
		'params' : {}
	};
	document.write('<scr' + 'ipt type="text/javascript" src="http' + (location.protocol === 'https:' ? 's' : '') + '://www.profitabledisplaynetwork.com/04cb581b5b5d8ea1dfaea16b4704b721/invoke.js"></scr' + 'ipt>');
</script>

Ad 3

<script type='text/javascript' src=‘//pl18677734.highrevenuegate.com/13/09/d0/1309d0b737bafe56cc10dd27dc1dedd2.js'></script>

Ad 4 

<script type="text/javascript">
	atOptions = {
		'key' : '1ede14b63ca80a84ac496af8e34904fa',
		'format' : 'iframe',
		'height' : 50,
		'width' : 320,
		'params' : {}
	};
	document.write('<scr' + 'ipt type="text/javascript" src="http' + (location.protocol === 'https:' ? 's' : '') + '://www.profitabledisplaynetwork.com/1ede14b63ca80a84ac496af8e34904fa/invoke.js"></scr' + 'ipt>');
</script>

Ad 5

<script async="async" data-cfasync="false" src="//pl18678072.highrevenuegate.com/0b05be5fd2da3e85f50cc87d94b05539/invoke.js"></script>
<div id=“container-0b05be5fd2da3e85f50cc87d94b05539"></div>

Ad 6 

<script type="text/javascript">
	atOptions = {
		'key' : 'f8002b73b6f7eafb027582a333bb7745',
		'format' : 'iframe',
		'height' : 300,
		'width' : 160,
		'params' : {}
	};
	document.write('<scr' + 'ipt type="text/javascript" src="http' + (location.protocol === 'https:' ? 's' : '') + '://www.profitabledisplaynetwork.com/f8002b73b6f7eafb027582a333bb7745/invoke.js"></scr' + 'ipt>');
</script>

Ad 7

<script type="text/javascript">
	atOptions = {
		'key' : '9441dc99c2451acd6bdf6e91442cdceb',
		'format' : 'iframe',
		'height' : 90,
		'width' : 728,
		'params' : {}
	};
	document.write('<scr' + 'ipt type="text/javascript" src="http' + (location.protocol === 'https:' ? 's' : '') + '://www.profitabledisplaynetwork.com/9441dc99c2451acd6bdf6e91442cdceb/invoke.js"></scr' + 'ipt>');
</script>

Ad 8

<script type='text/javascript' src='//pl18678635.highrevenuegate.com/b2/88/d0/b288d02c1112b46b7eaee18beadff32d.js'></script>

**Comment by gerardyadav** [comment]
Hi I added the Full Xpath and selected Element Finder as Slector All, its working but its showing 0,0 - 0 action, 0 batch, please help

**Comment by Dhruv-Tech-Apps** [comment]
There are two types of iframe one with src and one without src

### with src
You need to create separate configuration with src as url 


### without src
It can be configured within main page configuration itself . Enable check iframe first from action settings

**Comment by gerardyadav** [comment]
thank you
