### ISSUE TITLE
not possible to extract 3rd character from string

### ISSUE THREAD

**Issue by arunvijaycool** [Dhruv-Techapps/auto-click-auto-fill#298]
Cant able to copy and paste the particular character generated from the element. String option not working. 
![Capture](https://user-images.githubusercontent.com/127591942/224475324-c3234090-f8b8-4816-8651-10efb907786f.PNG)

**Comment by arunvijaycool** [comment]
i need to copy third character "B" only.

**Comment by dharmesh-hemaram** [comment]
Changes are deployed
