### ISSUE TITLE
Breaks some pages

### ISSUE THREAD

**Issue by rayman89** [Dhruv-Techapps/auto-click-auto-fill#30]
This addon breaks some pages like for example when you are logged on newgrownds clicking on the play button does nothing. Disabling this addon brings back the functionality.

**Comment by aburke20** [comment]
Have the same exact issue, my Uni's Webmail and Mcgrawhill Connect webpages get completely "frozen/blocked" if auto click is enable, despite not having anything point towards them on my end.

**Comment by Dhruv-Techapps** [comment]
Hi,

We have updated our extension with few major changes. Can you please re check and let us know if above issue still exist.

**Comment by Dhruv-Techapps** [comment]
Closing issue due to no response
