### ISSUE TITLE
add custom notifications on differnt clients or send message on when 1 click is doneon discourd 

### ISSUE THREAD

**Issue by Sana857** [Dhruv-Techapps/auto-click-auto-fill#304]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dharmesh-hemaram** [comment]
Currently we support notification on discord . and we dont have scope to add any other client

**Comment by Sana857** [comment]
But I am already paid
