### ISSUE TITLE
JS Window reload

### ISSUE THREAD

**Issue by Frerk-d** [Dhruv-Techapps/auto-click-auto-fill#305]
Im using A JS to reaload websites which will be then clicked with acf but since last update this works not really because acf say Error, it needs 2 Reloads per hand until acf is doing stuff again. But if the JS reloads the window it doesnt.

**Comment by dharmesh-hemaram** [comment]
With latest version build on MV3 this is blocked by browser. You can try legacy version for same https://legacy.getautoclicker.com/

https://github.com/Dhruv-Techapps/auto-click-auto-fill/discussions/283
