### ISSUE TITLE
We need Chinese, can you come up with a Chinese language?

### ISSUE THREAD

**Issue by luosaidage** [Dhruv-Techapps/auto-click-auto-fill#313]
**Is your feature request related to a problem? Please describe.**
My friends are not very good at English, I want to share this extension program with them, but they will be confused when they see the English interface, so please translate into Chinese.

**Describe the solution you'd like**
translate .

**Describe alternatives you've considered**
no.

**Comment by dharmesh-hemaram** [comment]
Hi @luosaidage ,

we would be very happy to add a new language to our project. But we dont have knowledge of same. If you could help here it would be great help. all our languages are here in below repo. You can create a copy of english and translate same in chinese.

https://github.com/Dhruv-Techapps/acf-i18n/tree/main/locales

**Comment by luosaidage** [comment]
Hello, I have finished the translation work and submitted a pull request.

**Comment by dharmesh-hemaram** [comment]
@luosaidage  - we have deployed changes on DEV env you can check on https://dev.getautoclicker.com

**Comment by luosaidage** [comment]
Ok,very nice!
