### ISSUE TITLE
click isssue

### ISSUE THREAD

**Issue by damtox** [Dhruv-Techapps/auto-click-auto-fill#36]
Hello i have issue - It only click 2 times then going to next step
I used
Init wait 2s  xPath //*[@id="gwiazdeczki"]/div[1]/div[1]/a[5]  repeat 4  interval 1
and 
Init wait 11s xPath //*[@id="nextpop"] repeat 0 interval 0

site is https://www.zdrowyportal.org/10866/rady-na-sprawne-stawy/   
i want to click on starts (5 star) 

PLZ HELP <3

**Comment by Dhruv-Techapps** [comment]
It seems the website is updated and the [xpath](https://dhruv-techapps.github.io/auto-click-auto-fill/docs/xpath) you have provided is no longer correct. Can you please re-check and update us
