### ISSUE TITLE
How to auto click?

### ISSUE THREAD

**Issue by ViettubCydicom** [Dhruv-Techapps/auto-click-auto-fill#41]
I want to click button "Click here to continue" on http://oke.io/. How?
![capture](https://user-images.githubusercontent.com/38202503/38876945-befbdc96-4287-11e8-9368-9aef583360dd.PNG)

**Comment by perfectenschlag** [comment]
![img_0210](https://user-images.githubusercontent.com/43225207/45461821-e7440600-b6b9-11e8-9f0f-f7f5e7244644.jpg)
How would I make an Xpath for an autoclicker that would click this every 5 seconds?

**Comment by dharmesh-hemaram** [comment]
Can you please export your configuration and send us on dhruv.techapps@gmail.com we will try to reproduce your issue and fix the same.
