### ISSUE TITLE
Value and saved websites disapear

### ISSUE THREAD

**Issue by arizman** [Dhruv-Techapps/auto-click-auto-fill#61]
For some reason the values and all saved websites disappear after a couple days of using it, and at the same time can no longer add any more values & websites. I have to remove and re-install the extension to get it to work again. Is there something i'm doing wrong or is this a known issue.

**Comment by dharmesh-hemaram** [comment]
We haven't heard such issue from anyone before can you please explain more in detail to look into the issue.

you can also mail us on dhruv.techapps@gmail.com

**Comment by dharmesh-hemaram** [comment]
Closing this issue as no response.
