### ISSUE TITLE
Can't add actions 

### ISSUE THREAD

**Issue by frammnm** [Dhruv-Techapps/auto-click-auto-fill#62]
Hello, 

I just downloading the plugin and my objective is to auto click a button every numer of seconds. To do this i added the url but i can't add actions, so i cant specify which element should be clicked. Overall the plugin idea seems great but feels like it needs work. 
Anyways if some kind of support can be done it would be great.

**Comment by Dhruv-Techapps** [comment]
This issue is already fixed. Please update the plugin version 2.0.55
