### ISSUE TITLE
It does not work properly

### ISSUE THREAD

**Issue by mmolaei5173** [Dhruv-Techapps/auto-click-auto-fill#66]
Unfortunately, after installing the extension it does not work properly. Please see attached file. No add button works. there is no filling area to input texts. please help.
![Untitled](https://user-images.githubusercontent.com/53506440/62186608-220b6700-b37c-11e9-9898-ef752c5ddd4a.jpg)

**Comment by Dhruv-Techapps** [comment]
We have updated our extension with few issues. Hope your issue also got resolved with same. Can you please update our extension to V2.0.55 and recheck if issue is fixed or not.
