### ISSUE TITLE
Add URL

### ISSUE THREAD

**Issue by oshitomo** [Dhruv-Techapps/auto-click-auto-fill#67]
I saw that we add a specific URL only.
In case the URL changes a part of itself, how can we add that URL to auto click?

EX: The first URL is "google.com/001"
then, the URL changes apart from "001" to "002" --> "google.com/002"
In this case, I'd like to add a URL like "google.com/***". And *** means the number from 001 to 999

**Comment by Dhruv-Techapps** [comment]
You can use [regular expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) pattern in [URL](https://dhruv-techapps.github.io/auto-click-auto-fill/docs/configuration#url).

Please try URL - google.com/.*

[Click here](https://dhruv-techapps.github.io/auto-click-auto-fill/docs/configuration#examples) to find more examples of URL
