### ISSUE TITLE
I cant pay in chrome

### ISSUE THREAD

**Issue by koyeongjo** [Dhruv-Techapps/auto-click-auto-fill#68]
![image](https://user-images.githubusercontent.com/29597584/63519579-34696280-c52e-11e9-8b64-e85b3be5db11.png)

I want to use the pro version, but I cant. And chrome pay didn't work.

How can I get the pro version? Please tell me the method.

**Comment by koyeongjo** [comment]
Upper picture said "You cant use the chrome pay now. You didn't complete payment. Please try it later."

T_T ....

**Comment by Dhruv-Techapps** [comment]
You can do payment through PayPal and get subscribed manually.

Below are subscription charges:
* 01 month : 01$ + 0.052$ (conversion Fee  : 01 * 0.052) + 0.35$ ( PayPal Fee ) = 1.402$
* 03 month : 03$ + 0.156$ (conversion Fee  : 03 * 0.052) + 0.35$ ( PayPal Fee ) = 5.506$
* 06 month : 06$ + 0.312$ (conversion Fee  : 06 * 0.052) + 0.35$ ( PayPal Fee ) = 6.662$
* 12 month : 12$ + 0.624$ (conversion Fee  : 12 * 0.052) + 0.35$ ( PayPal Fee ) = 12.974$

[PayPal Subscription](https://www.paypal.me/DharmeshH)

* Please share the transaction id once payment is done.
* Also share your email id which you want to register for full version.

Thanks,
dhruv.techapps@gmail.com
