### ISSUE TITLE
problem when try to open many a href 

### ISSUE THREAD

**Issue by egphp** [Dhruv-Techapps/auto-click-auto-fill#71]
at this website

https://w2.akoam.net/*/*

i use 

//a[text()="تحميل مباشر"]

url expamle 

https://w2.akoam.net/167239/%D9%85%D8%B3%D9%84%D8%B3%D9%84-La-Reina-del-Sur-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-%D8%A7%D9%84%D8%A7%D9%88%D9%84-%D9%85%D8%AA%D8%B1%D8%AC%D9%85

what happen it's open same url many times 

please help

**Comment by Dhruv-Techapps** [comment]
Extension finds all the links which are matching the given [xpath ](https://dhruv-techapps.github.io/auto-click-auto-fill/docs/xpath) and click synchronously all links. But then its upto site how it react when multiple links are clicked simultaneously.
