### ISSUE TITLE
I can't make autoclick in link-to.net

### ISSUE THREAD

**Issue by dogos1** [Dhruv-Techapps/auto-click-auto-fill#73]
If you go into below link and click "continue" button,It will appear "Go to website" button.But It is impossible for me to make autoclick on this "Go to website" button.
Is there anyone know how to make autoclick on this "Go to website" button?

https://link-to.net/26117/699.304521389714/dynamic?r=aHR0cDovLzE2My4xNzIuODMuMTQ1L2RlYi9hcGkvYXBpMDUvP2Fkcz1hSFIwY0Rvdkx6RTJNeTR4TnpJdU9ETXVNVFExTDJSbFlpOWhjR2t2WVhCcE1EUXZQMlJzUFRBMVpXSmhZelkzT0dabE1qaGpZUT09

![test](https://user-images.githubusercontent.com/26139424/66249289-c7233100-e76b-11e9-835a-1e6bf1dd7c94.png)

**Comment by Dhruv-Techapps** [comment]
Please try below configuration:
`{"initWait":"2","xpath":"//div[contains(@class,\"d-xl-block\")]/div[contains(text(),\"Continue \")]"}{"initWait":"15","xpath":"//span[contains(text(),\"Go to\")]"}
`
