### ISSUE TITLE
Cannot export configuration

### ISSUE THREAD

**Issue by TuanBC** [Dhruv-Techapps/auto-click-auto-fill#74]
Thank you for making such a great extension. However, with the current version, I cannot export the configuration to a json file to use it in another computer. 

Also, some more suggestions. It would be better if there is a way to rename the config instead of naming it with the URL. And also, a better way to change the position of the actions and configs would make this extension perfect to me :)

**Comment by dharmesh-hemaram** [comment]
Please refer [Export/Import Guide](https://dhruv-techapps.github.io/auto-click-auto-fill/docs/settings#export--import)
