### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LeJoris** [Dhruv-Techapps/auto-click-auto-fill#77]
Under the conditions there is no "not equal" selection. I often want to do actions when some field is not equal to some value and as the field is a number formatted as a string "greater" or "smaller" comparisons doesn't work. Equal works but not equal would be a lot better, please add. (but first conditions should work with refreshing)

**Comment by Dhruv-Techapps** [comment]
@LeJoris Thank you for your suggestion we will add this new condition in our next release and update you.

**Comment by Dhruv-Techapps** [comment]
#### Thank you for using our extension

We have added your required feature in v(2.0.60).

For more details on Addon condition [click here](https://dhruv-techapps.github.io/auto-click-auto-fill/docs/addon)
