### ISSUE TITLE
Saving issues

### ISSUE THREAD

**Issue by LeJoris** [Dhruv-Techapps/auto-click-auto-fill#78]
Sometimes my changes doesn't get saved. I redo changes over and over again and it just doesn't change. The only solution I found is to export configuration, edit it and then import it and then my changes are there but obviously it shouldn't be like that.

**Comment by Dhruv-Techapps** [comment]
Sorry for that inconvenience we have updated our configuration section with new tech stack hope this issue will get resolved with it. It will be fixed in V2.0.55
