### ISSUE TITLE
I want to know How click alert confirm

### ISSUE THREAD

**Issue by snaphers** [Dhruv-Techapps/auto-click-auto-fill#79]
I want to click the confirm in alert window.

Can I click confirm using by xPath?

If there is a way please let me know Thank you.

* This is really really helpful tool.

**Comment by Dhruv-Techapps** [comment]
Sorry confirm box is chrome custom button and it don't have any XPath . but we are working on it. to figure out some work around for same.

**Comment by dharmesh-hemaram** [comment]
`Alert Box` and `Confirmation Box` blocks UI Thread on which scripts run and it's not possible until we override the existing browser API. 
For now, we are closing this ticket but in the feature, if we find a feasible solution we will bring that changes into our extension
