### ISSUE TITLE
Customized Name for each action

### ISSUE THREAD

**Issue by hejdannymej** [Dhruv-Techapps/auto-click-auto-fill#81]
Hello, 

Congrats on the new update, the new interface looks amazing :) 
In the spirit of this new update, I would like to propose a suggestion is to add Customizable name for each configuration. 

At the moment, I've set up 20 actions for the same domains, it is getting a bit difficult to identify the purple of each action, so very often, I have to go through each action to see what they are used for. It will be a life saver if I can rename each action so if some error happens in the future, I can just navigate directly to that action.

Is that a viable thing to do? Thank you so much! 

Daniel

**Comment by Dhruv-Techapps** [comment]
Thank you for using our extension. Its available from v(2.0.60).

please [click here](https://dhruv-techapps.github.io/auto-click-auto-fill/docs/action#name) to get more details on same
