### ISSUE TITLE
Ability to double click

### ISSUE THREAD

**Issue by hejdannymej** [Dhruv-Techapps/auto-click-auto-fill#84]
Hi guys,

Thank you for developing such great extension. It's been super helpful for the past few months.

Recently, I have encountered one problem is that some feature on the website can only be activated using **_Double Clicks_**. 

I have tried to insert Repeat Value of each action by 2 but it doesn't seem to resemble the behavior of a Double Click. I'm wondering if there is anyway to achieve this?

In case the extension is not supporting Double Click at the moment, is it possible that you develop this feature as well? Thank you so much for your effort.

**Comment by Dhruv-Techapps** [comment]
### Thank you for using our extension

It available with new version (2.0.60).

Please check [docs](https://dhruv-techapps.github.io/auto-click-auto-fill/docs/action#click-events-examples) on how to make use of same
