### ISSUE TITLE
dropdown not working in my chrome browser

### ISSUE THREAD

**Issue by Deepjyoti120** [Dhruv-Techapps/auto-click-auto-fill#85]
please solved my issue dropdown not working in my chrome browser

**Comment by Dhruv-Techapps** [comment]
Can you please share the URL and Xpath of dropdown on which you are trying to automate.

You can also try on our [test page](https://dhruv-techapps.github.io/auto-click-auto-fill/test)

### Xpath - //select[@name="cars"]
### Value - audi

**Comment by Deepjyoti120** [comment]
wowwww awesome thanks
