### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by Deepjyoti120** [Dhruv-Techapps/auto-click-auto-fill#86]
Hi , I am Deejyoti
i have a questions if dropdown menu changed in every form how to select 1st item in dropdown menu

**Comment by dharmesh-hemaram** [comment]
Currently its selected based on value provided. But we see this option is worth adding. Will inform developers to add ability to select value based on index.

**Comment by Deepjyoti120** [comment]
thank you I am waiting
