### ISSUE TITLE
About autostart

### ISSUE THREAD

**Issue by Jrecord131** [Dhruv-Techapps/auto-click-auto-fill#87]
Hello, thank you for this app at first and startime dont working at all, app dont wotn to start, and sometimes app "freezing", dont click or fill fields about 10-15 seconds

**Comment by Dhruv-Techapps** [comment]
@Jrecord131 

> Thank you using our extension.

To verify you have inputted correct value for start time please check examples [here](https://dhruv-techapps.github.io/auto-click-auto-fill/docs/configuration#examples-1)

Page load time can affect the start time of extension. Extension will get invoke and check for start time only once whole page is loaded completely. You can change the extension load from window -> document level from [settings screen](https://dhruv-techapps.github.io/auto-click-auto-fill/docs/settings#extension-load).

You can test our extension on [Test Page](https://dhruv-techapps.github.io/auto-click-auto-fill/test) to see if start time is working correct or not.
