### ISSUE TITLE
Ability for a keyboard action

### ISSUE THREAD

**Issue by nictkwu** [Dhruv-Techapps/auto-click-auto-fill#90]
Similar to the double click option where the 'Enter' key needs to be pressed.

**Comment by Dhruv-Techapps** [comment]
Hi,

### Thank you for using our extension.

You can try `FormEvents::["submit"]` to submit the form. [click here](https://dhruv-techapps.github.io/auto-click-auto-fill/docs/action#form-events-examples) to know in more details
