### ISSUE TITLE
error when installed, "Package is invalid. "

### ISSUE THREAD

**Issue by libhugh** [Dhruv-Techapps/auto-click-auto-fill#91]
When i install it on my chrome on Window 10,  it shows a error that:

**Details: 'Could not load javascript 'content_scripts.min.js' for content script.'.**

Can not update and fix.

OS: Windows 10
Chrome version :   79.0.3945.88 (64-bit)

But it runs well in my Macbook.

OS: MacOS Version 10.13.6
Chrome version :   79.0.3945.88 (64-bit)

Please help me to fix it, i am using it in a VIP project, many people are wait for this extension,  thanks

**Comment by dharmesh-hemaram** [comment]
This issue has been fixed in last release. We apologies for inconvenience caused.
