### ISSUE TITLE
Cannot access options page.

### ISSUE THREAD

**Issue by SengthongD** [Dhruv-Techapps/auto-click-auto-fill#92]
When I click on the icon it takes me to the getautoclicker.com page with no options. It seems to redirect from index.html to just the getautoclicker.com page. 

This makes it unusable since I cannot access the options page to change xpaths or see them.

**Comment by dharmesh-hemaram** [comment]
**This issue has been introduced because of cache files in browser to load faster.**

### Please clear cache in your browser and reinstall extension from chrome webstore to fix same.

**Comment by androidkade11** [comment]
Hi
The settings for the fixed page are fine, but I want to use the page whose url changes

**Comment by Dhruv-Techapps** [comment]
Closing this issue as its working fine now and its not re occurring.
