### ISSUE TITLE
problem when try to get pro with macos google chrome

### ISSUE THREAD

**Issue by egphp** [Dhruv-Techapps/auto-click-auto-fill#95]
![Screen Shot 2020-01-11 at 9 52 49 AM](https://user-images.githubusercontent.com/35516754/72201014-7a30b400-3458-11ea-9857-82cc47a0fd94.jpg)

when i try tp get pro , get error 

that's shows with mocos google chrome

**Comment by Dhruv-Techapps** [comment]
Try our [BETA ](https://chrome.google.com/webstore/detail/auto-clicker-autofill-bet/faeeclonpikbempnbjbbajfjjajjgfio?hl=en&authuser=0) version. We are removing the Subscription part and keeping it open for all users for free.

Soon after testing this BETA version will be available to Stable version of AutoCliker as well.
