### ISSUE TITLE
i want to click on button only once.

### ISSUE THREAD

**Issue by RAJUP0685** [Dhruv-Techapps/auto-click-auto-fill#96]
Hi sir, this extension clicks on button continously. i need it to click only once. 
please help.
Thank you

**Comment by Dhruv-Techapps** [comment]
If you have entered values for [batch repeat](https://getautoclicker.com/docs/batch#repeat) / [action repeat](https://getautoclicker.com/docs/action#repeat). It will click continuously. Please do trial on our [Test page](https://getautoclicker.com/test).

If you still face issue send us your exported configuration from extension on dhruv.techapps@gmail.com

**Comment by eec17** [comment]
Hi sir, this extension clicks on button continously. i need it to click only once.
please help.
Thank you

@Dhruv-Techapps
 
Owner
Dhruv-Techapps commented 12 days ago
If you have entered values for batch repeat / action repeat. It will click continuously. Please do trial on our Test page.

If you still face issue send us your exported configuration from extension on dhruv.techapps@gmail.com


having this same issue also saying my subscription expired when i purchased today thanks!

**Comment by eec17** [comment]
issue occurs when trying to auto click a button from a drop down menu

**Comment by Dhruv-Techapps** [comment]
Can you please share your configuration by exporting same . We will try to reproduce issue our end

**Comment by eec17** [comment]
here it is

**Comment by Dhruv-Techapps** [comment]
Can you re check . You haven't added config file

**Comment by Dhruv-Techapps** [comment]
Closing this ticket as no response .
