### ISSUE TITLE
Incremental values when auto refresh

### ISSUE THREAD

**Issue by TuanBC** [Dhruv-Techapps/auto-click-auto-fill#99]
I'm quite excited with the beta version since I could try the refresh feature that may really useful when executing tasks in batch automatically. Currently, I'm trying to create multiple accounts on a website. However, it is not very useful to refill the exact same information everytime since the username needs to be different. I think a new feature like auto incremental variable in a range could be added so that everytime the page is refresh, it will fill a different information into a field.

**Comment by Dhruv-Techapps** [comment]
Hi @TuanBC ,

we are working on creating excel integration where extension can pull data from excel and on every refresh use new records from excel.

**Comment by dharmesh-hemaram** [comment]
Hi @TuanBC ,

[Beta version](https://chrome.google.com/webstore/detail/auto-clicker-autofill-bet/nmcpliniiebkbdehpgicgfcidgkpepep?hl=en&authuser=0)

Now you can add **`<batchindex>`** / **`<actionindex>`** in value to be replace with index of batch / action 

e.g. **myemail`<batchindex>`@gmail.com** in value 

In first iteration its value will be myemail1@gmail.com
on batch repeat 2nd iteration its value will be myemail2@gmail.com
on batch repeat 3nd iteration its value will be myemail3@gmail.com
